as yet unclassified
exampleExecution2
	
	| foo bar |
	foo := 42.
	bar := 'Cheese'.
	^ #V3;<~"98E%":+u-!!ElE@r,RpF!,OGEckl6F`M%"!!!!$"q!b4@ruF'DIIR2"98E%*=)WF!%S'V!!!!$
"q*_<F)PQ&@<?4%D?^>;DKKH&ATA%V!!!$&z#ljr*!t##.!'CGh6#q!SGmFBM!!*3&!!!!*!!!!$
$31&+49cB`EcPT6ARn/HCi!ZmFD5Z2#QOi)!<`B&!!!<*!!!*.!!!!]"r:-KEHPi1@qB(XCh5tP
Ci!ZmFD5Z2#QOi)!<`B&!!!<*!!!*.!!!!]"pRk4C1Ums#QOi)!<`B&!!!<*!!!*.!!!!]"q4FP
EbTE(88i<TATA%V!!!*(z&IN&[E+NotASuU2&I;lbDKKH-FE7`g!!!*.!!!!]"pRhFD.7's#QOi)
!<`B&!!!<*!!!*.!!!!]"qaXOA7]dmA4(9OCh7*uBl@kp!!!!%"98E%!"fBCEcPT6&IN,aEcZ=o
DId='&IE8^F*'ukA7]ud#ljr*!t##.!'CGh9lFQRC^:"@!!39'!!!!+!!!$*#ljr*!t##.!'CGl
9jq[PBlnK.AI&89!!*3&!!!!"#ljr*!t##.!'CH"9OVsSAPd;dBln'4AP$c]AS5Rp#QOi)!<`B&
!!!<*!!!*.!!!!]"q<mu;Fbb9E+hsaA7]Q_!!!!'"98E%!"ffQ@:Nt^A5dSgEb/0kEbTE(&I`Su
BkM-t@;JnSG]XN'G%kN36t(1G&I!&jA7]fo"_D4WATJ.X!!!*.!!!!]"pmtADejK794`AS!!!!#
"98E%!"f<KAU+R^!!!*.!!!!]"q!_9Ci!ZmFD5Z2#QOi)!<`B&!!!$+!!!!$$31&+49c'hF`'Kc
Eaa5!!!!!'"98E%!"f?SF`)74#'OEkF_,V+$#F$kF@g@\AU"dlCghC,;KZjh$>a-lFAHL\F(KFo
!=8`+!!<Q.!!#+g!!!!]#QOi)!sAT(!!!?+!!6^D"a4<jF_(jZ!!!*.!!!!]"q+7JDffnn@VTIa
F9hjH!!*3&!!!!"#ljr*!t##.!'CGo6<$iMDe*ERDe*Eq#QOi)#Qt,-!!!?+!!*?4!!!$6&J\eu
EcP`/F@0t`E+s-"A5-WWBQ%Dn%V'EpFCf?3F&R@$@W-&p&8cQ+FD4fjDId[0;flGiAJ#&TDe*Dk
#^0onG=5k]@0lo6!!<Q.!!#+c$pmok7ri$WBMNJVAI&89!!39'!!!!2"_):d@quAN!!!*.!!!!]
"p@n:G]X2k!!!*(z&I*;uEbTE(&Hm,sDK?*a!!!*.!!!!]"pn1=@ru-sB5D,b!!!!$"98E%!"fER
EbT0#D@m(_DfT`,EX;^G!!<Q.!!#+c$:9#[AQ*kk@W-&g!!!!""98E%!!rW*!!<Q.!!#+c$:9#[
AQ*\kBl7Ph!!!!""98E%!!rW*!!<Q.!!#+c'LGbs6"4nWEa`I"7ri$WBMNJVAI&89!!*3&!!!!*
!!!!$$31&+49c!gH#7#/C^:"@!!*3&!!!!*!!!!$$31&+49c!gFE2)5B*\J;!!*3&!!!!*!!!!$
$31&+49cNe<)Q"kF*)G2@rt%RDe!QWDe*Eq#QOi)"9\])!!!?+!!3T:!!!'C$31&-/cc7Y!!!*.
!!!!]"q!_9A7\;MCh.*t#QOi)"p=o+!!!?+!!*?4!!!$6$31&.9F:b""(MZ<!!@9K!!!!$$31&+
49bscDeX*2#QOi)!sAT(!!!T3GS't%!<E3%!<Ec@F*2G5EarooF)to6#ljr*!t##.!$DCE!!"#F
!!!!L!=8`+!!<Q.!!#+g!!!!j$31&,-j]kR!!<Q.!!#+g!!!"M$31&+W!NG(!!<Q.!!#+g!!!"t
$31&-F9qpI!!<Q.!!#+g!!!#K$31&.#RLJ2!!<Q.!!#+g!!!"2$31&+JI);V!!<Q.!!#+g!!!#g
$31&,M?s7_!!<Q.!!#+g!!!$J$31&,WX/Y*!!<Q.!!#+g!!!$f$31&+Vu[2)!!!*.!!!!]$31&,
M@'=`!7V;T!!!*.!!!!]$31&,WX8_+!7V#U!!!!$$31&+4:2&g!Qk`L!!#Rs!!!!$$31&+4:2&g
!V?^!!!L+E!!!!$$31&+4:2&g!`04(!!0)+!!!!$$31&+4:2&g!d"bL!!(LL#ljr*!t##.!'CSg
!!8Dm!!!"M!<EK,!!!*.!!!!]$31&+4:2&g!`01'!!!*.!!!!]$31&.#S@/VBl!eV!!!!$$31&+
4:2&g""FWX!!N3+!!!!$$31&+4:2&g".oo#!!HX8!!!!$$31&+4:2&g"3:fL!!%QV!!!!$$31&+
4:2&g"7QWt!!(LT!!!!$$31&+4:2&g"<RsN!!J,b!!!!$$31&+4:2&g"@!4n!!K,)!!!!$$31&+
4:2&g"CDK9!!(LT!!!!$$31&+4:2&g"GmHc!!K,)!!!!$$31&+4:2&g"JlG*!!%QV!!!!$$31&+
4:2&g"MkEF!!(LL#ljr*!t##.!'CSg!!N3,!!!#g#ljr*!t##.!'CSg!!P4e!!!#K!<E3%!<EK,
!!!31!!!&l!=8`+!!<Q.!!C:S%<H)sAftZ0@;Tt"AMFJk!!!31!!!(c#QOi)!<`B&!"B26!!!$*
z!<E3%#ljr*":>,/!CR1n!!!-.!!!!#$31&.T*YJt!!io3!!=\O&HDh4!>,WbDf0,/.NgKp!=8`+
!!3K-!!Ai"!!!!)$31&..KKkV!!k7Z!<EcAHRDU*A0<6N+E)./I/sWS!!!'-!!!+n#ljr*#RUP3
""F<Y!!!9Y!<E35+a\-FAKYE&;fm%oDJ(LC-QmABCh7Z1De:+>/0K%YDg_Wm!!!!#$31&.T*YJt
!!io3!!=\O$31&30ED1T&INksDf76N@UX;*!<`B&!!*3&!!!-.!!!!%$31&,6jNbm!"'#4!!!*.
!!!!]$31&3Y6k70#TF'M!!!*.!!!!]$31&3)[ZQF#]9qK!!!*.!!!!]$31&3Y6k70#XJas!!!*.
!!!!]$31&35mdSl#]9YD!<E3%"98E%!<`B&!!E~>