defaults
defaultForm

	 ^ #V2;BTRImageModel;43A;Constant1;ColorForm;421;Form1;<~M,6r;%14!\!!!!.8Ou6I!!!!S!!!!S#Qk&,!%HlOK)blR!)Q?g7K9>eWa>c$2ZWlP7]Kbps.i2m
NXGP:!<8`[pacEF<ri+Q!306'Wi/pt>l^gT!9D_2W`oJ'M(na*8b5(Fs-uHVJ,nYr2:Y\,s.).6
QoV0H!84BLn)rI*g8aC0!<;`ap](<oW`?'R!8:EQqN6L/<<fL(!9rCErJ<P;WeL<Eo_D9<s/MF_
<=8VrQ24K\rNrc8Wg9ZL9Di$Lq+Lec<=5au<WB1tXG[4]JcP^U1\!p7ZB[`,M$`rA!;TV\oM[L*
RmltLKBc_Lh4RcTU/g5N!30$!W`]>,KLu4Ezzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
zzzzzzzzzzzzzzzzzzzzzz!5V1\WrN,#!-D+6;ZQjts8W-!s8W-!s8W-!s8W-!s8W-!s8W-!s8W-!
s8W-!s8W-!s8W-!s8W-!s8W-!s8W-!s8W-!s8W-!s8W-!s8W-!s8W-!zzzzzzzzzzzzzzzzzzz
zzzzzzzzzzzzzzzzzzzzzzzzzz!65G;R/d3f.S3#o<-V`gPtd=V+:s8J5-5Z_eP.rK0RNOjA).+a
a*_IP8h4<$d/'7:aqG-+^hUeZ$sC8U!MpEC5,rFa;P`_O&,@?[Q7]Ld$;kN6Bc<uD+-FrSLW\#.
Qi\KA'\U;0;d,lDa7+k4qutM@^\lJIlS==uHOl0'PIT53*tUZ$]aUQaoJunDfm!^YlG/0s%U<S(
CmlrKn.$FkYh<"m<pI8f<aQ@@,sU?:B2s+@C)k+&.*S+8#F'S[U2#O6SNA(UnHbY+)!o$&@1oY%
F.ikZ7a\Po/tPU(Wq(!1P@(Q3<Rosh*:u0u9ECLC4$R^j]WL*^m'D<#oNH(r4Y!7d*kmNd'Ahh>
'l.$m>+:#%]7g+mH`'m*HqILME@"hS1FP1Lr"`YN+e$[V!!!!j78?7R6=>B~>;;