defaults
defaultForm

	 ^ #V2;BTRImageModel;43A;Constant1;ColorForm;421;Form1;<~M,6r;%14!\!!!!.8Ou6I!!!!S!!!!S#Qk&,!%HlOK)blR!)Q?g7K9>eWa#Q!2ZWlP7]KYms.i2j
NX,>7!<8`[pacEF<<2nO!30-$Wi/pt=obLQ!9D_2W`T8$M(na*8b5(Fs-uHVJ,nYr2:Y\,s.).6
QoV0H!84BLn)rI*g8aC0!<;`ap](<oW`?'R!8:EQqN6L/<<K7$!9rCBrJ<P8WeL<Eo_D9<s/MF_
<<rDoQ24K\rNWH/Wg9ZL9DhpIq+Lec<<oOr<WB(qWf$nXJcP^R1\!p7YE_E)M$E`>!;TV\oM[L*
RmltLKBcVFh4RcQU/g5N!30$!W`B,&KLu4Ezzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
zzzzzzzzzzzzzzzzzzzzzz!;pV)QiI*e!-D+6;ZQjts8W-!s8W-!s8W-!s8W-!s8W-!s8W-!s8W-!
s8W-!s8W-!s8W-!s8W-!s8W-!s8W-!s8W-!s8W-!s8W-!s8W-!s8W-!zzzzzzzzzzzzzzzzzzz
zzzzzzzzzzzzzzzzzzzzzzzzzz!65G;R/d3f.S3#o<-V`gPtd=V+:s8J5-5Z_eP.rK0RNOjA).+a
a*_IP8h4<$d/'7:aqG-+^hUeZ$sC8U!MpEC5,rFa;P`_O&,@?[Q7]Ld$;kN6Bc<uD+-FrSLW\#.
Qi\KA'\U;0;d,lDa7+k4qutM@^\lJIlS==uHOl0'PIT53*tUZ$]aUQaoJunDfm!^YlG/0s%U<S(
CmlrKn.$FkYh<"m<pI8f<aQ@@,sU?:B2s+@C)k+&.*S+8#F'S[U2#O6SNA(UnHbY+)!o$&@1oY%
F.ikZ7a\Po/tPU(Wq(!1P@(Q3<Rosh*:u0u9ECLC4$R^j]WL*^m'D<#oNH(r4Y!7d*kmNd'Ahh>
'l.$m>+:#%]7g+mH`'m*HqILME@"hS1FP1Lr"`YN+e$[V!!!!j78?7R6=>B~>;;