defaults
defaultForm

	 ^ #V2;BTRImageModel;43A;Constant1;ColorForm;421;Form1;<~M,6r;%14!\!!!!.8Ou6I!!!!S!!!!S#Qk&,!%HlOK)blR!)Q?g7K9>eWb;D-2ZWlP7]L)$s.i3!
NYD1C!<8`[pacEF?i^'Z!30Q0Z)Cs.AcSc]!9D_3Wal+0M(na*8b5(Fs-uHVJ,nYr2:Y\,s.).6
QoV?O!84TRn)rI*g8aC0!<;`ap]LTsW`?*S"klrVqN6L/<=cH:!9rCNrJ<PDWeL<Eo_D9<s0.je
<tkJ(Q24ferOo_SWg9ZL9Di?Uq+Lec<YMO+<WBM([>PKoJckpa1\!p7]9P\5M%]SJ"8Pq_oM[L*
RmltLKBd%^h4Rc]U/g5N!309(WaYt>KLu4Ezzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
zzzzzzzzzzzzzzzzzzzzzz!8L&4kPtS`!-D+6;ZQjts8W-!s8W-!s8W-!s8W-!s8W-!s8W-!s8W-!
s8W-!s8W-!s8W-!s8W-!s8W-!s8W-!s8W-!s8W-!s8W-!s8W-!s8W-!zzzzzzzzzzzzzzzzzzz
zzzzzzzzzzzzzzzzzzzzzzzzzz!65G;R/d3f.S3#o<-V`gPtd=V+:s8J5-5Z_eP.rK0RNOjA).+a
a*_IP8h4<$d/'7:aqG-+^hUeZ$sC8U!MpEC5,rFa;P`_O&,@?[Q7]Ld$;kN6Bc<uD+-FrSLW\#.
Qi\KA'\U;0;d,lDa7+k4qutM@^\lJIlS==uHOl0'PIT53*tUZ$]aUQaoJunDfm!^YlG/0s%U<S(
CmlrKn.$FkYh<"m<pI8f<aQ@@,sU?:B2s+@C)k+&.*S+8#F'S[U2#O6SNA(UnHbY+)!o$&@1oY%
F.ikZ7a\Po/tPU(Wq(!1P@(Q3<Rosh*:u0u9ECLC4$R^j]WL*^m'D<#oNH(r4Y!7d*kmNd'Ahh>
'l.$m>+:#%]7g+mH`'m*HqILME@"hS1FP1Lr"`YN+e$[V!!!!j78?7R6=>B~>;;