as yet unclassified
initialize

	super initialize.
	self
		newForm: #V2;BTRImageModel;43A;Constant1;ColorForm;421;Form1;<~M,6r;%14!\!!!!.8Ou6I!!!!S!!!!S#Qk&,!%HlOK)blR!)Q?g7K9>fX*XjA2ZWlP7]Lb7s.i34
N[FNV!<8`[pacEFErc(m!315C`2IXTGlXdp!9D_FZ$-2QM(na28b5(Fs-uHVJ,nYr2:Yn2s.).6
QoW#u!858en)rI*g:QTA!<;`ap_Nr1Y%YP((tr$kqN6L/@Nrj(!9rCarJ<PWYD)iJo_D9<s213#
C*rhNQ25K-rQra7\X'ai9Dj#hq+MFuBdUQd?iS6EaGV1CJen921\!p=cBU]HM'_p](AV#toM[L*
RmltXKBd_/h4RcpU0ckW!5*4MZZQ8mKLu4Ezzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
zzzzzzzzzzzzzzzzzzzzzz!3Tm_63$ud!-D+6;ZQjts8W-!s8W-!s8W-!s8W-!s8W-!s8W-!s8W-!
s8W-!s8W-!s8W-!s8W-!s8W-!s8W-!s8W-!s8W-!s8W-!s8W-!s8W-!zzzzzzzzzzzzzzzzzzz
zzzzzzzzzzzzzzzzzzzzzzzzzz!65G;R/d3f.S3#o<-V`gPtd=V+:s8J5-5Z_eP.rK0RNOjA).+a
a*_IP8h4<$d/'7:aqG-+^hUeZ$sC8U!MpEC5,rFa;P`_O&,@?[Q7]Ld$;kN6Bc<uD+-FrSLW\#.
Qi\KA'\U;0;d,lDa7+k4qutM@^\lJIlS==uHOl0'PIT53*tUZ$]aUQaoJunDfm!^YlG/0s%U<S(
CmlrKn.$FkYh<"m<pI8f<aQ@@,sU?:B2s+@C)k+&.*S+8#F'S[U2#O6SNA(UnHbY+)!o$&@1oY%
F.ikZ7a\Po/tPU(Wq(!1P@(Q3<Rosh*:u0u9ECLC4$R^j]WL*^m'D<#oNH(r4Y!7d*kmNd'Ahh>
'l.$m>+:#%]7g+mH`'m*HqILME@"hS1FP1Lr"`YN+e$[V!!!!j78?7R6=>B~>;;;
		position: #V2;BTRNumberModel;1F;Constant1;SmallFloat64;5;1;0.0;; @ #V2;BTRNumberModel;1F;Constant1;SmallFloat64;5;1;0.0;;.
	