as yet unclassified
testCreationForMorph

	| model |
	model := BTRConstantModel for: #V2;BTRMorphModel;AF0;Constant1;Morph;ADB;1;<~n%6=^7WNEa+B*9&ART@3/i"PfAfrfa+@KdNASkmfEZd+k0fU:[CghEsF*&OIE+EC!ANCqY0fUpD
3*dYFDBLq^6#^jYC`kJe0f^@bF<ED$2)%'I0d(FP-Qrp.+\uQ^ARfg\@ps7mATAo2ATo82DJ=3,
@;KY(AK_Kl%1OJ%ASbs$F)>?+FAc[^;fm%k@;R.j!!!!%#QOi)";)/SCghC++EMXFF^oN9Eb,OW
!!!**$:JT<FD5Z2@<-Vr!!!!;#QOi).ffqV!!!**$UJiTDe!KiFD5Z2"p[_;FCf)rEX2XF!!*3&
!!!!*!!!!$$31&+49cB`EcPT6ARn/HCi!ZmFD5Z2#QOi)!<`B&!!!<*!!!*.!!!!]"qF@GEc>\\
G][M7F(oQ1#QOi)$j6P1!!!T8Ci<g!ARlAXG%l#3@VfTf#'4m#@r$?%$Y!O\Ci=60<+U;r&JJV^
Ci"$.DH(1lFAlaeARfh#EY/^kG][M;DII?V@;TQf$u'cZ@<-I26uQs]EY/Xe@ruX0;flGiAJ#,c
CghU#EY/^kG%GQ587?CHCh7W!%rZQ'ATCUfDfB9.FD5<-#ljr*!t##.!'CGh6#q!SGmFBM!!*3&
!!!!*!!!!$$31&+49cR"AT;j(DI[6d@VfUCDes6$@ruF'D?p4B!!*3&!!!!*!!!!$$31&+49c?f
@<6*nA4(9OCh7*uBl@kp!!!!$"98E%!"fBV@;Kb*&HuT`Eaa5"!!!!$$31&+4:2&g!$DOI!!!*(
z$31&,SdGGt!Mp)&!!!*.!!!!]"qaXOA7]dmA4(9OCh7*uBl@kp!!!!%"98E%!"fBCEcPT6&IN,a
EcZ=oDId='&IE8^F*'ukA7]ul!!!!$$31&+49bsVDes?4#QOi)"9\])!!!T5EbAhn$Y*UTBOt^B
AT2a)&J/G\@q]Fa6>:O<@<?U&Ec)0`!!!*.!!!!]"pRk4C1Ums#QOi)!<`B&!!!<*!!!*.!!!!]
"pn"4B5VF*F_#%h!!!!""98E%!!rW*!!<Q.!!#+c##9;X@V'Qc!!!!""98E%!!rW*!!<Q.!!#+c
'MMqUB4XnXF(o`1G%F6_FCf)rEX2XF!!*3&!!!!*!!!!$$31&+49c-[Des6$@ruF'D?p4B!!*3&
!!!!*!!!!$$31&+49c*cDf9E6E(abf#QOi)!X&K'!!!T5CLqbl!=8`+!!<Q.!!#+c"\ioUE+fLW
!!!6,z&I)]_F`(`2&I!)sDImi#$$15uD/XH6BQFamAp%p+6>q!aA9/=d@rH1%EY/UhG][M7F(oQ1
!<EK,!!!*.!!!!]$31&+49toe!!<?(!!!!+!!!*7&I!>dCis:q!!!!$$31&+49c0iEc6&<:L\'M
@rqtV!!!$&z!<EK,!!!*.!!!!]"pn1=@ru-sB5D,b!!!!$"98E%!"fEREbT0#D@m(_DfT`,EWHIH
!!!*.!!!!]"q!\BFCeBrD.7F"#QOi)!<`B&!!!$#!=8`+!!<Q.!!#+c$UScPA7]d[FEq\6#QOi)
!<`B&!!!<*!!!*.!!!!]"pS"JEbTE(#QOi)!<`B&!!!<*!!!*.!!!!]"pS"OD.7F"#QOi)!<`B&
!!!$##ljr*!t##.!'CGh:iC&cF9hjH!!<?(!!!!2!I,1WGl[pH#ljr*!t##.!'CGu8RuCMFD5iB
6tp.QBl@ltEd7oj!!!*(z$31&,SdGGt!Mof'!!!!$$31&+49c!VBln3#E!QFD!!*3&!!!!2%!-Q1
ATD9s@<6L$EsVgH!!<Q.!!",E!!!!;#QOi).ffqV!!!*.!!!!]$31&+8I>Ft!gj8o!!!*.!!!!]
$31&+AdSM<!EKL,!!!*.!!!!]$31&,<XJg,!o=4`!!!*.!!!!]$31&+N=#Xc!aQ*4!!!*.!!!!]
$31&,JdMJX!o=4`!!!*.!!!!]$31&->m^Q3".ff!!!!*.!!!!]$31&,3skrf!+lN;!!!*.!!!!]
$31&,fa7]Z!EKL,!!!*.!!!!]$31&++:8)K!J1UX!!!*.!!!!]$31&-QjNfn!dP(P!!!*.!!!!]
$31&-GmXNO!aQ*4!!!*.!!!!]$31&-*XVlI!aQ*4!!!*.!!!!]$31&-ZjHd5!(dIs!!!*.!!!!]
$31&-h?j5_!aQ*4!!!*.!!!!]$31&-rX&W*!dOeI#ljr*!t##.!'CSg!!=JR!!!(+!<EK,!!!*.
!!!!]$31&+4:2&g!r`K+!!!*.!!!!]$31&.Se2'BBl!eN#ljr*!t##.!'CSg!!C%E!!!(+!=8`+
!!<Q.!!#+g!!!,k$31&/;#p[u#ljr*!t##.!'CSg!!EuC!!!(+#ljr*!t##.!'CSg!!G.d!!!"2
#ljr*!t##.!'CSg!!H.+!!!-Z!<EK,!!!*.!!!!]$31&/D[HIE!aPg-!=8`+!!<Q.!!#+g!!!.c
$31&++9;cK!!!*.!!!!]$31&/`X2\G!+lN;!!!62!!!*H%h;Dk&TCnS#QOi)!!*B+!!!-/!!!'A
"98E(rr`<%!$DZ""p"u/!!*$*!!!!-$31&+N<94a!<E3'!<E3-!!!!$$31&/P6:jc!!<K,!!!0'
!=8`+!!<Q.!!#+c$Y"$pA7]d[FEq\6#ljr*!=Af,";D.B!!!*.!!!!]"qbojB5V-o6Z6j[ARfgr
Df0V&!!!!$$31&++9VZE!!!9)!!!*%!<EK,!!!*.!!!!]"q"dVBl.:#Bl@m1#ljr*":>,/!SI_Y
!!!?,!<E3%!<E3%!<`B&!!*3&!!!!B%1N~>;;.
	self assert: (model isKindOf: BTRMorphModel).