as yet unclassified
testCreationForImage

	| model |
	model := BTRConstantModel for: #V2;BTRImageModel;9AC;Constant2;UndefinedObject;5;1;nil;UndefinedObject;5;1;nil;Form;968;Form1;<~M,6r;%14!\!!!!.8Ou6I!!!"G!!!"@#R18/!2YfPWW3#(/4i5q<-Va2SNF"o723eUT8&Y-?se7t
hh6NA8<JW:#s*a$O@Y!,6:.E';FHWt4pHEb)JWFog(\7!Uf_fQGB,(O1NUj0h=](;^Gtdof=Ue&
DpNK2X4-=_S\X;u\%e$L[dDX)]+;h$UYe_`G9;/b,Nes54Ts*;ZJ-JSF6p=$[>iOKY>4ks0;+'6
\&VrCA&g,'HX$X+I3@=#7.O14_nLcj!hg1fJ5,K@7&.$\)B&uK5NBYqHgcQZNB.9PCK@F&pVHP(
Q!+08c-?SQ]rlqH")]6lTMf3fcgG]p@CqL31SqOb-nL3^[ccA"Lq[WJ\5_ZZJZmb?*06/,q;a+(
_h5*Tgig='k_5Q/,R&?^qbpp%lMq=ICDLjb7c&l--NGi(Is7Nm!Gk#m@IGjIUQDIa^oXW`hqplm
f#lYBoq-GTI+V:P:4;fg1tr4!RrDi:>Ok&Ok6uAN`+a2U/mR*'E]Ebn`Ot+$^M/&Ak+V'Ic0+&t
iGTRK%5*?@`t`*\L2.=_m>heTfA$%L)`2BVa8#e.d!)W`o54p`[:nSNiqT6rHOLP\HO[2kQ:0&(
jNU]H6GF&-?MLb.jKg:?2^ba/[X/E)[KlMP,]$$ip@e3dma7q>F:TFAIXXM8ctf'8)_5M(+1A(@
3i?S252.s,>+tJ<\NYI!DBiVg?pYfW:,=MR/TCmJrU=U_:9PJ9='loTIH^0/0+9pS.T:aR4[6>@
LMt0?L5iCi<uS^_o%>>)etcVA+CW<J./:"sORBI_9'p41!d4uk88J=$,omCp9Xj4<E6K\7a+`t%
mX`4KfnjZXibNW<#<tJS">C'&+*PVRVss:Vjk3n*X"VeBh89RAmW@STf!hdOg"bM=d-p4=47"Ho
Nf`#sa+Oi/Um`m_H;:fQ2<,tbec^8[Y\Sp8JZ!Icl.+#IOSEX>fF%e*K/IPjRV%.<f$QH@Cjan1
Y\SlN#hkWFBmd?I5f8AJO`kLtS*T=u1`mh5K%2gI>jrqG,D5.$Xn]+NpY-UYc';[([;gTH)&-2#
YVaaOf$QH@kY'/q?0))/G/<9=I+TR=gt1@2l2HWaEA$+?/T$;f03?uqB2/-_7K'*2.a?7Rn:Cr:
mnNQKj/-%_mcEa^:%oF!Hs2LIQi-GnIMr2Ns/,&[mbe&l%\KABhr)DT%JHVTh3U:kmGg69CMMVZ
3SDp%;]FciO+V'Enj<MCL)$oF.?3ib[pGhhhu9S=r];tkJJoNp[ha'=s1E"f$7o,n?DKK^#6!l$
7fW@kWBT4"%6p^RR*30QbB@G%gSA.VUVH]+l!F$[pn-G%h-WD,BQm.VZObD>s0PM6W,/*a_j66f
.F*ksGDm4F)]tkn\o=UVmJ?0O*f^cC^hR%dUrpZVKr[Zqpop)$'sKEE&%XH&*g,%)nR6&3/Q=5B
4#cM@Gr?Sb3JJDm3sJ8hON\W9Q)qMVN@CJ,2SL%^?ig?mCnQW7;bdJ6LRiE2buZ_>1O1',cd'&!
ig]4#U[qU,$m.AkCjamG_PTLYgH6DsGhVMGfZ9;YI5X9*H-.G$U76!VNXm'N2SLkd[:=h&6=r>!
f_E82VXOA5/9edK\u6XY?7J/*%%#c-2J_DPYJlj]^kW7")]uS=jeO)!07;E`>.A+hmF\4b`I0X.
m!2uOCW>mqqf?P#fDlQ<.Z-m4\9"uZ]+c?-(q'ScS%(ssCDP^ALRlh5Q=DCXfrdr+%iZTK53r8c
N>\Y[U+O+0'0bb:Cp)qOqd(q'i3K@#5&>W!ponPhfWE9r%=e*o\Rt^C*-.L-&%b`l^1B=o@2B9?
Sr4,kd.P\[>:dDUggNdJ>'MskNT9K5],r&dBf8mC@V>UB$7;4DRj:X:);*_dTBnIUWsQFLcRga8
:paLkll=u*KDB!bbt8?j;j_S!]-:Z:"^Wt\;Z\WE0[/L^X+EJ^plm'La2""rM_9=r?,(V?4t$95
CO0d@1-Y%TK/X7EfsYPH[YM2B[SPuH5\j8kPgh4,*6O45`Rd?s^tp0-&2eb)S=7_$#$/&jfX?@4
<gR46V6Cd)ili"CdHm$D2EpI6@?3/%P3Frrrt"K/P%)H$@:*0DnH6-,?utGQ0sEO$!?_"D_Ubc7
%A*_\^1M!`Ha@L?NB]m2[Hj-4I(ifGoh?NK5J,h3RrOM8?B^tY=G_*8Q_ej\5/(W)!8A6PCL70%
GJ9k#:".:?%m/,CN"6j5p/F4;AKNPh_h8PI,])4+S*_i=l6QndXo[9O/b,V+a@a6@^eP&m%m'mG
=u3>Od?8S@@:o^I;k?]TbM;t^_N(`cEc6C;_0&AW!SZ1TEN)aSf5)d!$YaCX;af>n3L=@<_k%G5
k$/jt&%8?E2C7_i!TDVO>qU<-?2ss*!(fUS7'8jaJc~>;;.
	self assert: (model isKindOf: BTRImageModel).