as yet unclassified
testCreationForMorph

	| model |
	model := BTRConstantModel for: #V2;BTRMorphModel;ADA;Constant1;Morph;AC5;1;<~n%6=^7WNEa+B*9&ART@3/i"PfAfrfa+@KdNASkmfEZd+k0fU:[CghEsF*&OIE+EC!ANCqY0fUpD
3*dYFDBLYg+@0seBl"nI0JPR1@<<VH0fh'F3]/T6@;RA8%1OIV@VTIaFAl[XDJj$++Dtb7+DG_-
FD50"BmO>6%1NaU+`h42Afu/3@<-HfAS+k_Eb/Zr+TqcF!!EQ-!!!-6%qBEaF)rIFFE2M6FEMV8
#ljr*!sT*#Bk)7!Df0!(Gm"*I!#c+C!!"MM#ljr*!sT-!F)u80Bjl*tDf,aa8T&W]B4Z)h!!!!"
"98E%!!rW*!!<Q.!!#+c&OCGX@<lEp6Z6dWARfgrDf,g\!!!$&z#ljr*!t##.!'CGq9lG&kBLR/f
ASuR'Df,g\!!!E1z&I*&i@r#Xd&I3JnF(o*"AJ#,fFD56#GnCEn@;KauDf/NcG]XN2@UX(hDf9Mm
AU&;qASbpfFDl13$tX[*ATDZsCeeDUAJ#>bF&6:cFE9igDJsP-$=RFdDfScu@<?&m#&nBeH"D".
$tXTnDKJEXDIdQpEY/h#FD,6+:i^JnATDm,ATJ.X!!!*.!!!!]"pI;5Eaa5!!!!!""98E%!!rW*
!!<Q.!!#+c(/ndaF_,H#ART%aAOCBPCh7*uBl@kp!!!!""98E%!!rW*!!<Q.!!#+c&4g5NBOt^A
Des6$@ruF'D?p4B!!<?(!!!!2"a"0hCj?Tr@<-BsGmOHN!!<Q.!!#+g!!!!A#QOi)!sAT(!!!?+
!!/Yu!!!%r#ljr*!t##.!'CGt:NBuWEb/cKDes6$@ruF'D?p4B!!EE)!!!!2"^uFl@<iFlAnc:,
F@g@\AU"dnCghC,8T&'MGR4?M!!<Q.!!#+c"[d3EDfQ*`!!!-)z&Hd&d@M&uX@:Nt^A41!JFD)6t
@prk\ARn,AFAQCfFCfK1#ljr*!t##.!'CGi:L\'M@rqtV!!!$&z#ljr*!t##.!'CGl9jq[PBlnK.
AI&89!!*3&!!!!*!!!!$$31&+49c!bF_tT!EX2XF!!*3&!!!!*!!!!$$31&+49cKn@<-!l:iCDh
FD5o08T&W]B4Z)h!!!!""98E%!!rW*!!<Q.!!#+c$:A`JCh7*uBl@kp!!!!""98E%!!rW*!!<Q.
!!#+c#u#8UCNXShAU+O]!!!''z&Hcf[Gl[pP!!!!$$31&+49bs`DfTf1#QOi)#6Y#,!!!T8@W-C,
A9/=dDg-)1EY/V!F^f3+Ec>]5&IN,mChuFVF`(`2&HuZ_Ci=>+$"\@'ASuR'Df,RV#ljr*!t##.
!'CSg!!#+e!!!!$"98E%!"&]+!tu7MG%#30AI/>:!!<Q.!!#+c$W(k^FDjraC1Ums#QOi)!<`B&
!!!$##ljr*!t##.!'CGl;Is?[@;]^oAI&89!!<?(!!!!2#&eNrB5)5q#%MRlDImhh#ljr*!t##.
!'CGm6@!Za;gE4hDeo[Z!!!$&z!<E3-!!!!$$31&+49c0[DfTB"E`7(*Ch3kP!!!$&z#ljr*!t##.
!'CGi;fm%oDJ'4T!!!$&z#ljr*!t##.!'CGi;gE4hDeo[Z!!!$&z!<EK,!!!*.!!!!]"pIhABl8"u
!!!!$"98E%!"f6V&HR.X!<EK,!!!*.!!!!]"qjL<ASuU(FEp8g@ruF'DIIR2#QOi)!sAT(!!!?+
!!/Yu!!!%r!=8`+!!<Q.!!#+c#"!$GD..Ah!!!!""98E%!"fW\F`:o4@r,RpF(KD!!!!!$$31&+
+9VZE!#c+C!!"MM#ljr*!t##.!'CSg!!#Rt!!!(f#ljr*!t##.!'CSg!!$U<!!!%##ljr*!t##.
!'CSg!!-+-!!!)W#ljr*!t##.!'CSg!!%uc!!!(+#ljr*!t##.!'CSg!!.ZY!!!)W#ljr*!t##.
!'CSg!!6F5!!!+m#ljr*!t##.!'CSg!!,.g!!!"2#ljr*!t##.!'CSg!!1a[!!!%##ljr*!t##.
!'CSg!!",K!!!%O#ljr*!t##.!'CSg!!8Mp!!!(G#ljr*!t##.!'CSg!!7EQ!!!(+#ljr*!t##.
!'CSg!!42K!!!(+#ljr*!t##.!'CSg!!9M7!!!!j#ljr*!t##.!'CSg!!;!a!!!(+#ljr*!t##.
!'CSg!!<-,!!!(G!<EK,!!!*.!!!!]$31&.,ROMO!aPg-#ljr*!t##.!'CSg!!#+g!!!*"#ljr*
!t##.!'CSg!!Af)")_gh!<EK,!!!*.!!!!]$31&._$U/B!aPg5!!!!$$31&+4:2&g"7Z]u!!H."
!<EK,!!!*.!!!!]$31&/'FFg?!aQ*4!!!*.!!!!]$31&/2$s<`!+lN;!!!*.!!!!]$31&/;$m:'
">p2\#ljr*!t##.!'CSg!!I3I!!!(+!<E3-!!!!$$31&+4:2&g"Hs/m!!",B#ljr*!t##.!'CSg
!!L:K!!!"2#ljr*#7:G2"!eBe:biW%=oem/!!!!"#ljr*":>,/!ZhIE!!E6(!!!!A$\/E^#QFc(
rs8Z*!"927!!%u\!WrH(!<W?'!=8`+!!<Q.!!JJg!!!!$#QOi)"T\W1!!!!$$31&+49c1&DfTB"
E`7(*Ch3nQ!!!$,!!!-9#ljr*!t##.!'CGtF(o9)@;J;LDJj#qFD5Z2EsVgH!!<Q.!!",Ez#QOi)
!s&E'#ljr*!t##.!'CGm@;]dr@<?4%DK?*a!!!-/!!!&Q#QOi)$3:/.!<E3%!<E3(!!!!""98E%
!$Md\~>;;.
	self assert: (model isKindOf: BTRMorphModel).