as yet unclassified
testValueReturnsValue

	| model color |
	color := #V3;<~"98E%":+u-!!ElE@r,RpF!,OGEckl6F`M%"!!!!$"q!b4@ruF'DIIR2"98E%'aOd>!%S'V!!!!$
"q*_<F)PQ&@<?4%D?^>;DKKH&ATA%V!!!$&z#ljr*!t##.!'CGt6#q!SH"CMRDes6$@ruF'D?p4B
!!*3&!!!!*!!!!$$31&+49cR"AT;j(DI[6d@VfUCDes6$@ruF'D?p4B!!*3&!!!!*!!!!$$31&+
49c?f@<6*nA4(9OCh7*uBl@kp!!!!$"98E%!"fBV@;Kb*&HuT`Eaa5"!!!!$$31&+49bsTEcPT6
#QOi)!<`B&!!!<*!!!*.!!!!]"pRk4C1Ums#QOi)!<`B&!!!<*!!!*.!!!!]$31&++:%rI!!<?(
!!!!+!!!#L$31&+g^*r\!!<Q.!!#+c##9;X@V'Qc!!!!""98E%!!rW*!!<Q.!!#+c"[d3EDfQ*`
!!!-)z&Hd&d@M&uX@:Nt^A41!JFD)6t@prk\ARn,AFAQCfFCfK1!=8`+!!<Q.!!#+c#u+i@DJ=38
A7Z#H!!!$&z!=8`+!!<Q.!!#+c'MMqUB4XnXF(o`1G%F6_FCf)rEX2XF!!*3&!!!!*!!!!$$31&+
49c-[Des6$@ruF'D?p4B!!*3&!!!!"!<E3%!=8`+!!<Q.!!#+c$W(k^FDjraC1Ums#QOi)!<`B&
!!!$#!=8`+!!<Q.!!#+c&40>o6Z6j`FCB'/9lFQRC^:"@!!NK*!!!!2&S#6ZBOt^QFDl22;fm%o
DJ'OiDfTQ)Bl7?q<+U;r&I<PoATpONFC>abG%#30AI/>:!!<Q.!!#+c#uY>EFCB'"Ch3kP!!!*(
z&I*/oBkM-t&I)``Ec,H/#ljr*!t##.!'CGm6@!Za;gE4hDeo[Z!!!$&z#ljr*!t##.!'CGp6<$iM
Des?49lFQRC^:"@!!NK*!!!!+!!!(!$31&-AdSM<!d"bL!!7TU!!!!$$31&+49cNe<)Q"kF*)G2
@rt%RDe!QWDe*Eq#QOi)"9\])!!!?+!!6(+!!!(4$31&-F9)[J!!!*.!!!!]"pS"OD.7F"#QOi)
!<`B&!!!<*!!!*.!!!!]"pS"JEbTE(#QOi)!<`B&!!!$#!=8`+!!<Q.!!#+c"]0,ODKH-a!!!*(
z&HR+g!I4\H!<E3%&I``'E+O'"CghC+ATJ.X!!!*.!!!!A"98E%'aOd>!%S'V!!!!$$31&+4:2&g
!(dLt!!,Rr!!!!$$31&+4:2&g!+lQ<!!%ub!!!!$$31&+4:2&g!0%<c!!2Hn!!!!$$31&+4:2&g
!4`F:!!2Hn!!!!$$31&+4:2&g!=0#4!!3f?!!!!$$31&+4:2&g!::*n!!$U;!!!!$$31&+4:2&g
!$DUK!!'P9!!!!$$31&+4:2&g!CmIs!!/i$!!!!$$31&+4:2&g!FlH:!!*?+#ljr*!t##.!'CSg
!!/i%!!!$*!=8`+!!<Q.!!#+g!!!&;$31&+8I5@s!!<Q.!!#+g!!!&e$31&,#QXr,!<E3-!!!!$
$31&+4:2&g!YZ.JDJ<nf!<EK,!!!*.!!!!]$31&-NsYje!=/u3!!!*.!!!!]$31&-2[TNb!u2+B
!!!*.!!!!]$31&-^'Xi?"&K:(!!!*.!!!!]$31&-h?j5_!]LDc!!!*.!!!!]$31&.'aap@!=/]4
!!!!$$31&+4:2&g"&K=)!!@$D!!!!$$31&+4:2&g")J;E!!$U3!<EK,!!!*.!!!!]$31&.M[BFa
!=/],!<E3%#ljr*"UY50!o<qY#ljr*!t##.!$DCE!!!!)!!!!&!<E3%!=8`+!!EW/!!-R4!"]&1
!<E~>.
	model := BTRConstantModel for: color.
	self assert: color equals: model value.