as yet unclassified
testCreationForMorph

	| model |
	model := BTRConstantModel for: #V2;BTRMorphModel;AE7;Constant1;Morph;AD2;1;<~n%6=^7WNEa+B*9&ART@3/i"PfAfria+A-'[F^]<9+>PW*3?VOB@<?(%F<G^FA79Rk3ZoY%3&39E
>p+''+?:Q1E,oZ/+>PW*3?VaP+?;J=1cd?K+CT+7+Unl(:L\'M@rtXZ@;]soEZf72G9CU;Bln&t
Ch\3,+Unki%3]e(Ch=f2D..I,;IsH=FE1r$D'9#^!!!--!!!!%&J&Af@<6K4F*)GF@ruj6AI/>:
!!<E46tp.QBl@ltEd7cf!!!oC!!!!L!=8`+!!<E56$%*c@qf@nBl@kn#>&fTAS5Rp#QOi)!<`B&
!!!<*!!!*.!!!!]"qa.AEaa6)A4(9OCh7*uBl@kp!!!!""98E%!!rW*!!<Q.!!#+c%S^k^E+h[b
FCf?2Bl@kp!!!!-"98E%!"fEODe!QoA.]&iBldutCh41_F*),+CO$L"@UX(hDf9MmAU&;/'4PBd
Ci=60<+U;r;e9cV@ruX0&I`5qFCfK1@;J\ID.O:fBld*ZEcc@jDf0K6&IMrVFDl1uFCB9&&I*2j
@<lF)&I`5oASuT\@;]UlATA@nDffZ(E_pdpE+O'3Bk;>l!!!!$$31&+49bsTEcPT6#QOi)!<`B&
!!!<*!!!*.!!!!]"r:-KEHPi1@qB(XCh5tPCi!ZmFD5Z2#QOi)!<`B&!!!<*!!!*.!!!!]"qX=6
F(f,q6Z6dWARfgrDf,g\!!!*(z&I!8bCi"A/"^uFl@<i.Z!!!*.!!!!]$31&++:%rI!!<?(!!!!+
!!!%k$31&,V$R,%!!<Q.!!#+c&PmFXATD?m6Z6dWARfgrDf,g\!!!-)z&HuT`Eaa5*$>+!mF*'uk
A7]ut$#F$kF@g@\AU"L]!!!*.!!!!]"pIA4Ci=>"!!!!%"98E%!"f<RB4;G\@prk\ARn2?E-,b*
&7]-YBOt^@Blm0[FED)7D@$:C!!<Q.!!#+c##A]CARfff!!!!""98E%!!rW*!!<Q.!!#+c#u+i@
DJ=38A7Z#H!!!$&z#ljr*!t##.!'CGi:3CD_ATA%V!!!$&z#ljr*!t##.!'CH"9OVsSAPd;dBln'4
AP$c]AS5Rp#QOi)!<`B&!!!<*!!!*.!!!!]"q!_9Ci!ZmFD5Z2#QOi)!<`B&!!!<*!!!*.!!!!]
"pmtADejK794`AS!!!!#"98E%!"f<KAU+:W#ljr*!t##.!'CGh9lG&kBF"S<!!`W,!!!!2#%DLn
DIdf#"`JU&ATA@hF*1r/DfTf1EtJakF_kk\Dfor.EtJRcDes?4&IE#nFCf?2Bl@ki!=8`+!!<Q.
!!#+g!!!!]#QOi)!sAT(!!!?+!!<lH"a4<jF_(jZ!!!*.!!!!]"q+7JDffnn@VTIaF9hjH!!*3&
!!!!"!=8`+!!<Q.!!#+c#uY>EFCB'"Ch3kP!!!*(z&I*/oBkM-t&I)``Ec,H/!=8`+!!<Q.!!#+c
$:9#[AQ*kk@W-&g!!!!""98E%!!**$#ljr*!t##.!'CGn6>pmTATC^kH#.$t!!!!""98E%!!rW*
!!<Q.!!#+c##fVaBl7Ph!!!!""98E%!!rW*!!<Q.!!#+c##fea@W-&g!!!!""98E%!!**,!!!!$
$31&+49bscDeX*2#QOi)!sAT(!!!T3GS't%!<E3-!!!!$$31&+49cEiA7]Y#BlnVgBk)7!Df0!(
GmFBM!!<?(!!!!+!!!%k$31&,V#^l&!!!*.!!!!]"pRD.FDYH*#QOi)!<`B&!!!T>F*2G5Earoo
F)to6#ljr*!t##.!$DCE!!!oC!!!!L!=8`+!!<Q.!!#+g!!!!j$31&-QjE`m!!<Q.!!#+g!!!"2
$31&,<XAa+!!<Q.!!#+g!!!%#$31&-h?a/^!!<Q.!!#+g!!!"Y$31&->mUK2!!<Q.!!#+g!!!%O
$31&-h?a/^!!<Q.!!#+g!!!(+$31&.Sd>As!!<Q.!!#+g!!!$]$31&+AdJG;!!<Q.!!#+g!!!&Q
$31&,<XAa+!!<Q.!!#+g!!!!A$31&,JdDDW!!<Q.!!#+g!!!(f$31&-GmOHN!!<Q.!!#+g!!!(G
$31&->mUK2!!<Q.!!#+g!!!'A$31&->mUK2!!<Q.!!#+g!!!)-$31&+8I5@s!!<Q.!!#+g!!!)W
$31&->mUK2!!<Q.!!#+g!!!*"$31&-Gl[pP!!!!$$31&+4:2&g"!e3R!!6F,!=8`+!!<Q.!!#+g
!!!!]$31&-rWrQ)!!<Q.!!#+g!!!+m&HcobC]OPC!!!!$$31&+4:2&g"2P<E!!6F,#ljr*!t##.
!'CSg!!D`u!!!.!!<E3-!!!!$$31&+4:2&g";D1C!!6F4!!!!$$31&+4:2&g">pMd!!$U;!!!!$
$31&+4:2&g"AoL+!!G.[!=8`+!!<Q.!!#+g!!!.?$31&->las,#ljr*!t##.!'CSg!!JJm!!!!A
!=8`+!!<Q.!!#+g!!!/A$31&+AdJG;!!`i2!!=JW%T"nmE*<8Jz!=8`+!!EW/!!42E!!!-$"98E%
+:E](!=/W)!<3?*!!!E7!!!"Y!s/Q*!<E9'!<EK,!!!*.!!!.c"98E%!sel,!!NB(#ljr*!t##.
!'CGn@W-9tATC^kH#.$u!!!!"$31&/'F=a>!!<Q.!!#+c&T_Z!DII?KDf0H(@ruF'DK?*a!!!*.
!!!!A"98E%!!iQ)!!<6&!=8`+!!<Q.!!#+c$=RgdD..O#Df0V&!!!!%$31&,fa%QX!"&`-!<E3%
!<E3%"98E%!<`B&!!"/O%0~>;;.
	self assert: (model isKindOf: BTRMorphModel).