initialization
initializeFilenames
	self
		"player gifs"
		addFilename: 'player_stand_left.gif' 	atSymbol: #stand_left;
		addFilename: 'player_stand_right.gif' 	atSymbol: #stand_right;
		addFilename: 'player_jump_left.gif' 		atSymbol: #jump_left;
		addFilename: 'player_jump_right.gif' 	atSymbol: #jump_right;
		addFilename: 'player_run_left.gif' 		atSymbol: #run_left;
		addFilename: 'player_run_right.gif' 		atSymbol: #run_right;
		addFilename: 'Coin.gif' 					atSymbol: #Coin; "not used because it's buggy - not our fault"
		addFilename: 'crystal02.png' 			atSymbol: #diamond;	
		addFilename: 'Feuerblume.png'			atSymbol: #fireflower;
		addFilename: 'fireball.png'				atSymbol: #fireball;
		addFilename: 'target_flag.png'			atSymbol: #target_flag;
		addFilename: 'background.png' 		atSymbol: #background;
		addFilename: 'placeholder.png'			atSymbol: #placeholder;
		addFilename: 'platform.jpg' 			atSymbol: #platform;
		addFilename: 'campfire.png' 			atSymbol: #fire;	
		addFilename: 'ground_full.png' 			atSymbol: #ground;
		addFilename: 'rocky01.png' 			atSymbol: #rocky;
		addFilename: 'lava.png' 				atSymbol: #lava;		
		addFilename: 'gumba.png' 				atSymbol: #gumba;
		addFilename: 'squashed_gumba.png'   atSymbol: #squashed_gumba;
		addFilename: 'turtle.png' 				atSymbol: #turtle;
		addFilename: 'turtle_shell.png' 			atSymbol: #turtle_shell;
		addFilename: 'leafy_ground03.png' 	atSymbol: #leafyPlatform1;
		addFilename: 'leafy_ground04.png' 	atSymbol: #leafyPlatform2;
		addFilename: 'rocky02.png' 			atSymbol: #rockyPlatform1;
		addFilename: 'rocky04.png' 			atSymbol: #rockyPlatform2;
		addFilename: 'heart.png' 				atSymbol: #heart;
		addFilename: 'mushroom.png' 			atSymbol: #mushroom;
		addFilename: 'cat.png'					atSymbol: #cat.