as yet unclassified
testComposedExecution

	| expected |
	expected := #bar.
	self
		assert: expected
		equals:	#V3;<~"98E%":+u-!!ElE@r,RpF!,OGEckl6F`M%"!!!!$"q!b4@ruF'DIIR2"98E%*!cNE!%S'V!!!!$
"q*_<F)PQ&@<?4%D?^>;DKKH&ATA%V!!!$&z#ljr*!t##.!'CGt6#q!SH"CMRDes6$@ruF'D?p4B
!!*3&!!!!*!!!!$$31&+49bsTEcPT6#QOi)!<`B&!!!<*!!!*.!!!!]"r:-KEHPi1@qB(XCh5tP
Ci!ZmFD5Z2#QOi)!<`B&!!!<*!!!*.!!!!]"qX=6F(f,q6Z6dWARfgrDf,g\!!!*(z&I!8bCi"A/
"^uFl@<i.Z!!!*.!!!!]"pRk4C1Ums#QOi)!<`B&!!!<*!!!*.!!!!]$31&++:%rI!!<?(!!!!+
!!!#g$31&+pB^g"!!<Q.!!#+c$r_7gBl7QSDerrqEX2XF!!<?(!!!!2$=m^eASu$iDKKq3#\.dj
FCf?3EsVgH!!<Q.!!#+c##9;X@V'Qc!!!!""98E%!!rW*!!<Q.!!#+c"\ioGAS_VP!!!''z$31&,
?O6]4!!<Q.!!#+c#u+i@DJ=38A7Z#H!!!$&z!=8`+!!<Q.!!#+c'MMqUB4XnXF(o`1G%F6_FCf)r
EX2XF!!*3&!!!!*!!!!$$31&+49c-[Des6$@ruF'D?p4B!!*3&!!!!*!!!!$$31&+49c*cDf9E6
E(abf#QOi)!X&K'!!!T5CLqbl!=8`+!!<Q.!!#+c#Z>e_6#q!SGmFBM!!WQ+!!!!2"EJX&EtJV"
@;L'tEtJ^p@<6N^DId='&I3,\F*(<&D@m4l@<6NdAnH*qF9)CK!!!!$$31&+4:2&g!'CMe!!!*(
z$31&-3Y;O=@;L't#ljr*!t##.!'CGn:i^JrDbjhWARfff!!!!""98E%!!*B+!!!*.!!!!]"q3gt
;F>A5API)RAS_VP!!!9-z$31&,?O?c5!G`8^@s)g4ASuTWDf'H-Ch7-OATVU(A.];]Df0Z.DKKqu
H#7#/C_74qF_l/6=(uP_Dg,-%@<?&m"Cl@\AJ#2kBk;KV@<>oa!!!!$$31&+49bpfAU&;&!!!!$
"98E%!"fEVFE2)5B+Y8eF`)7,!!!!$$31&+49cBa<)Q&!De!QKFEDP;@Wcd(#QOi)!sAT(!!!T?
@;]RgDfTE"9lG&kBFtS\Ci<g!9lFQRC^C(A!!<Q.!!#+c#uY>EFCB'"Ch3kP!!!*(z&I*/oBkM-t
&I)``Ec,H/#ljr*!t##.!'CGm6@!Za;gE4hDeo[Z!!!$&z#ljr*!t##.!'CGm6@!Za;fm%oDJ'4T
!!!$&z!=8`+!!<Q.!!#+c##fea@W-&g!!!!""98E%!!rW*!!<Q.!!#+c##fVaBl7Ph!!!!""98E%
!!**,!!!!$$31&+49c-[De*EMDerrqEX2XF!!WQ+!!!!+!!!%,$31&,CC1%A!s/f0!!=)G!!!*M
#ljr*!t##.!'CGh:iC&cF9hjH!!<?(!!!!2!I,1WGl[pH!=8`+!!<Q.!!#+c%9-n`F?t"jEbT!*
FCb^X!!!$&z!>,`]F`:o4@r,RpF(KD!!!!!$$31&++9VZE!#u7E!!"MM#ljr*!t##.!'CSg!!#Rt
!!!%L#ljr*!t##.!'CSg!!$U<!!!"t#ljr*!t##.!'CSg!!&r)!!!'(#ljr*!t##.!'CSg!!(LU
!!!'(#ljr*!t##.!'CSg!!*?4!!!)7#ljr*!t##.!'CSg!!%uc!!!"2#ljr*!t##.!'CSg!!,Rs
!!!%h#ljr*!t##.!'CSg!!",K!!!#K#ljr*!t##.!'CSg!!.QV!!!&3#ljr*!t##.!'CSg!!/Pr
!!!$*#ljr*!t##.!'CSg!!0\=!!!$*!=8`+!!<Q.!!#+g!!!&S$31&+8I5@s!!<Q.!!#+g!!!'(
$31&,#RLJ2!!<Q.!!#+g!!!'H$31&,])_p=!!!!$$31&+4:2&g!_Wk#!!$U3!=8`+!!<Q.!!#+g
!!!!]$31&-,maPO!!<Q.!!#+g!!!)7&HcobC]OhB!!!*.!!!!]$31&-i!KGa"DJ/B!!!*.!!!!]
$31&.<=/^+!+lN;!!!*.!!!!]$31&.I0orS"NLfK!!!*.!!!!]$31&.^Bsr@!=/u3!!!*.!!!!]
$31&.mKrpo">:&]!!!*.!!!!]$31&/%LN19"A8b%!!!!$$31&+4:2&g">:)^!!Gq$!!!!$$31&+
4:2&g"A9(%!!$U3!=8`+!!<Q.!!#+g!!!.9$31&,7gT.q!!<Q.!!#+g!!!.r$31&,#QXr,!=8`+
!!<Q.!!#+g!!!/B$31&,#QY53!!!93!!!)Y!>,;4"pT-eF`Lu'!=8`+!!<Q.!!?45!<EK,!!!31
!!!'n#QOi)!<`B&!!*?*!!!$*!!!!"#ljr*!t##."+:1V!!!!)$31&-huO/b!!c4!$31&2:]Uk&
!!!*.!!!+$&I;rmE+NO$ARl)I!!!31!!!'n#QOi)!<`B&!!ii1!!!$*z!<E3-!!!!$$31&++9VZE
!!*?*!!!0'!<EK,!!!*.!!!!]"r1iiCh[cu<bZ,h:i^JnDfTr6Df0V&!!!!$$31&/U'(Gr!7V,O
!!#"[!<E3-!!!!$$31&++9VZE!!*?*!!!0'!<EK,!!!*.!!!!]$31&2r!<?'!!<Q.!!K#!!!!$0
"98E%;#p~>.