as yet unclassified
testReceiverIsCorrect

	self 
		assert: self methodUsingSelf 
		equals: #V3;<~"98E%":+u-!!ElE@r,RpF!,OGEckl6F`M%"!!!!$"q!b4@ruF'DIIR2"98E%)@-<C!%S'V!!!!$
"q*_<F)PQ&@<?4%D?^>;DKKH&ATA%V!!!$&z#ljr*!t##.!'CGt6#q!SH"CMRDes6$@ruF'D?p4B
!!*3&!!!!*!!!!$$31&+49bsTEcPT6#QOi)!<`B&!!!<*!!!*.!!!!]"r:-KEHPi1@qB(XCh5tP
Ci!ZmFD5Z2#QOi)!<`B&!!!<*!!!*.!!!!]"qX=6F(f,q6Z6dWARfgrDf,g\!!!*(z&I!8bCi"A/
"^uFl@<i.Z!!!*.!!!!]"pRk4C1Ums#QOi)!<`B&!!!<*!!!*.!!!!]$31&++:%rI!!<?(!!!!+
!!!#g$31&+pB^g"!!<Q.!!#+c$r_7gBl7QSDerrqEX2XF!!<?(!!!!2$=m^eASu$iDKKq3#\.dj
FCf?3EsVgH!!<Q.!!#+c##9;X@V'Qc!!!!""98E%!!rW*!!<Q.!!#+c"\ioGAS_VP!!!''z$31&,
?O6]4!!<Q.!!#+c#u+i@DJ=38A7Z#H!!!$&z!=8`+!!<Q.!!#+c'MMqUB4XnXF(o`1G%F6_FCf)r
EX2XF!!*3&!!!!*!!!!$$31&+49c-[Des6$@ruF'D?p4B!!*3&!!!!*!!!!$$31&+49c*cDf9E6
E(abf#QOi)!X&K'!!!T5CLqbl!=8`+!!<Q.!!#+c#Z>e_6#q!SGmFBM!!WQ+!!!!2"EJX&EtJV"
@;L'tEtJ^p@<6N^DId='&I3,\F*(<&D@m4l@<6NdAnH*qF9)CK!!!!$$31&+4:2&g!'CMe!!!*(
z$31&-3Y;O=@;L't#ljr*!t##.!'CGn:i^JrDbjhWARfff!!!!""98E%!!*B+!!!*.!!!!]"q3gt
;F>A5API)RAS_VP!!!9-z$31&,?O?c5!G`8^@s)g4ASuTWDf'H-Ch7-OATVU(A.];]Df0Z.DKKqu
H#7#/C_74qF_l/6=(uP_Dg,-%@<?&m"Cl@\AJ#2kBk;KV@<>oa!!!!$$31&+49bpfAU&;&!!!!$
"98E%!"fEVFE2)5B+Y8eF`)7,!!!!$$31&+49c*iARfgjDJ*cs#QOi)!sAT(!!!T8DfTQ)Bl4Le
@rHC*ATA(W!!!*.!!!!]"q!\BFCeBrD.7F"#QOi)!<`B&!!!<*!!!*.!!!!]"q!\BFCeBmEbTE(
#QOi)!<`B&!!!$##ljr*!t##.!'CGi;gE4hDeo[Z!!!$&z#ljr*!t##.!'CGi;fm%oDJ'4T!!!$&
z!<EK,!!!*.!!!!]"q!_9A7\;MCh.*t#QOi)"p=o+!!!?+!!-F6!!!%8$31&.!X\o-!uVFG!!=YV
!!!!$$31&+49bscDeX*2#QOi)!sAT(!!!T3GS't%!<E3%!<Ec@F*2G5EarooF)to6#ljr*!t##.
!$DCE!!!oC!!!!L!=8`+!!<Q.!!#+g!!!!j$31&,IgH)T!!<Q.!!#+g!!!"2$31&+W!NG(!!<Q.
!!#+g!!!"t$31&-"UP//!!<Q.!!#+g!!!#K$31&-"UP//!!<Q.!!#+g!!!$*$31&-^'Oc>!!<Q.
!!#+g!!!"Y$31&+AdJG;!!<Q.!!#+g!!!$i$31&,RgB&p!!<Q.!!#+g!!!!A$31&+e-Q*T!!<Q.
!!#+g!!!%L$31&,]*SH;!!<Q.!!#+g!!!%h$31&,#RLJ2!!<Q.!!#+g!!!&3$31&,#QY53!!!*.
!!!!]$31&,gBmo\!(dIs!!!*.!!!!]$31&-"UY50!=/u3!!!*.!!!!]$31&-,mjVP!P8@5#ljr*
!t##.!'CSg!!5e#!!!"2!<EK,!!!*.!!!!]$31&+4:2&g![S-Q!!!*.!!!!]$31&-^(CHbBl!eV
!!!!$$31&+4:2&g!oOCc!!F\V!!!!$$31&+4:2&g"'#[.!!$U;!!!!$$31&+4:2&g"+:LV!!*?3
!!!!$$31&+4:2&g"0;h0!!DWq!!!!$$31&+4:2&g"3_)P!!EW0!=8`+!!<Q.!!#+g!!!,h$31&/
$4-\4!!<Q.!!#+g!!!-/$31&+AcVo=!!!!$$31&+4:2&g"=OTW!!,Rr!!!!$$31&+4:2&g"CVW;
!!*?+!<E3%!=8`+!!io3!!;'Z&HDh9#'4^*EarY]#ljr*!t##."'#pIF(K0"+Dk\3BQ%E]F(oN)
;e9cW#ljr*"pt>1!_We!!!!$&!!!!5#QOi)!=/Z*!!!$#!=8`+!!<Q.!!",E!!!!"#QOi)!snr-
!!<Q.!!#+c'kqQ%Bl7K_Bk;KbEc5o8Ecc#6DK?*a!!!*.!!!.1"98E%M?EnZ!#>S9~>