as yet unclassified
testInlineExecution

	| x |
	x := 42.
	self assert: x * x equals: #V3;<~"98E%":+u-!!ElE@r,RpF!,OGEckl6F`M%"!!!!$"q!b4@ruF'DIIR2"98E%(^L*A!%S'V!!!!$
"q*_<F)PQ&@<?4%D?^>;DKKH&ATA%V!!!$&z#ljr*!t##.!'CGt6#q!SH"CMRDes6$@ruF'D?p4B
!!*3&!!!!*!!!!$$31&+49cR"AT;j(DI[6d@VfUCDes6$@ruF'D?p4B!!*3&!!!!*!!!!$$31&+
49c?f@<6*nA4(9OCh7*uBl@kp!!!!$"98E%!"fBV@;Kb*&HuT`Eaa5"!!!!$$31&+49bsTEcPT6
#QOi)!<`B&!!!<*!!!*.!!!!]"pRk4C1Ums#QOi)!<`B&!!!<*!!!*.!!!!]$31&++:%rI!!<?(
!!!!+!!!#L$31&+g^*r\!!<Q.!!#+c$r_7gBl7QSDerrqEX2XF!!<?(!!!!2$=m^eASu$iDKKq3
#\.djFCf?3EsVgH!!<Q.!!#+c##9;X@V'Qc!!!!""98E%!!rW*!!<Q.!!#+c"\ioGAS_VP!!!''
z$31&,?O6]4!!<Q.!!#+c#u+i@DJ=38A7Z#H!!!$&z!=8`+!!<Q.!!#+c'MMqUB4XnXF(o`1G%F6_
FCf)rEX2XF!!*3&!!!!*!!!!$$31&+49c-[Des6$@ruF'D?p4B!!*3&!!!!"!<EK,!!!*.!!!!]
"pe+LDF&;`@<i+Y!!!3+z&Hm,sDK?BoG%#30ATJFiCghC,8T&'MGS(0s@<6NgF`%cuCghC,:M+3[
ATRqR#ljr*!t##.!'CGn:i^JrDbjhWARfff!!!!""98E%!!**,!!!!$$31&+49c3\<)Q)%A7\JR
A7]Q_!!!!)"98E%!"&]+!FH06!!-jI'k;B,Eb0-16Z6g\Bl%?k9kAE[De'Fi@rH7,ASuU2;gE4h
Dep!sD09Z:Bif"dA8cZjFCB9&&HlT^A7Z>YG%kN36t(1G#ljr*!t##.!'CGg<+U;r#QOi)!sAT(
!!!T8F*)G:DJ'OaEcl8@#ljr*!t##.!'CGl;Is?[@;]^oAI&89!!<?(!!!!2#&eNrB5)5q#%MRl
DImhp!!!!$$31&+49c-ZH$!UrH#7#/C^:"@!!*3&!!!!*!!!!$$31&+49c-ZH$!UrFE2)5B*\J;
!!*3&!!!!"!=8`+!!<Q.!!#+c##fea@W-&g!!!!""98E%!!rW*!!<Q.!!#+c##fVaBl7Ph!!!!"
"98E%!!**,!!!!$$31&+49c-[De*EMDerrqEX2XF!!WQ+!!!!+!!!%,$31&,CC1%A!kSd>!!:RU
!!!)[#ljr*!t##.!'CGh:iC&cF9hjH!!<?(!!!!2!I,1WGl[pH!<E35%!-Q1ATD9s@<6L$EsVgH
!!<Q.!!",E!!!!9#QOi).ffqV!!!*.!!!!]$31&+8I>Ft!IkCU!!!*.!!!!]$31&+AdSM<!0%9b
!!!*.!!!!]$31&+N=#Xc!X/l1!!!*.!!!!]$31&+\I&<:!X/l1!!!*.!!!!]$31&,#RUP3!d4kM
!!!*.!!!!]$31&+m0Wgn!+lN;!!!*.!!!!]$31&,7g]4r!LjAq!!!*.!!!!]$31&++:8)K!4`C9
!!!*.!!!!]$31&,IgQ/U!P8X<!!!*.!!!!]$31&,RgK,q!=/u3!!!*.!!!!]$31&,]*\N<!=/]4
!!!!$$31&+4:2&g!S[q]!!#Rs!!!!$$31&+4:2&g!X/o2!!*?+!<EK,!!!*.!!!!]$31&--jfqS
!+l64#ljr*!t##.!'CSg!!7<U")_gh!<EK,!!!*.!!!!]$31&-R0ioo"5sOd!!!*.!!!!]$31&.
%LN19!+lN;!!!*.!!!!]$31&.2@9Ea!=/u3!!!*.!!!!]$31&.AI8D;"/cG*!!!*.!!!!]$31&.
KaIe["2b-?#ljr*!t##.!'CSg!!B,+!!!,=#ljr*!t##.!'CSg!!C+G!!!"2!<EK,!!!*.!!!!]
$31&.i<fPb!CmFr!!!*.!!!!]$31&/)@?HE!=/],!<E3%#ljr*#RUP3!gs'$!!*9.F)Q2A@q>ZI
!!!!$$31&.%M8kh+=\LY#ljr*"pt>1![n<S!!!$&!!!!&#QOi)!=/Z*!!!$#!=8`+!!<Q.!!",E
z#QOi)"T\W)!<E~>.