accessing
grammar: anObject

	self assert: anObject class = #V2;ReferenceBlock;B58;1;<~n%6=^7WNEa+B*9&ART@3/i"PfAfria+A-'[F^]<9+>PW*3?VOB@<?(%F<G^FA79Rk3ZoY%3&39E
>p+''+>Pr"9jr;i1,(FC+CT@70ek^E2``WQ+CT+7+Unl(:L\'M@rtXZ@;]soEZf72G9CU;Bln&t
Ch\3,+Unki%3]e(Ch=f2D..I,;IsH=FE1r$D'9#^!!!--!!!!%&J&Af@<6K4F*)GF@ruj6AI/>:
!!<E46tp.QBl@ltEd7cf!!!rD!!!!L!=8`+!!<E56$%*c@qf@nBl@kn#>&fTAS5Rp#QOi)!<`B&
!!!<*!!!*.!!!!]"pI;5Eaa5!!!!!""98E%!!rW*!!<Q.!!#+c%S^k^E+h[bFCf?2Bl@kp!!!!-
"98E%!"fEODe!QoA.]&iBldutCh41_F*),+CO$L"@UX(hDf9MmAU&;/'4PBdCi=60<+U;r;e9cV
@ruX0&I`5qFCfK1@;J\ID.O:fBld*ZEcc@jDf0K6&IMrVFDl1uFCB9&&I*2j@<lF)&I`5oASuT\
@;]UlATA@nDffZ(E_pdpE+O'3Bk;>l!!!!$$31&+49c9nAS,LoASu!h6>URMCBsn?!!rc.!!!!2
#%DLnDIdf#"`JU&ATA@hF*1r/DfTf1EtJakF_kk\Dfor.EtJRcDes?4&IE#nFCf?2Bl@l$&T;i(
Ecu/.G=-1TF)t)bD.O:`F*VV3Deo^[!!!*.!!!!]"qa.AEaa6)A4(9OCh7*uBl@kp!!!!""98E%
!!rW*!!<Q.!!#+c(/ndaF_,H#ART%aAOCBPCh7*uBl@kp!!!!""98E%!!rW*!!<Q.!!#+g!!!!A
#QOi)!sAT(!!!T7FCB!%GnC3gEcPT6#ljr*!t##.!'CGh6Z6dZEX2XF!!EE)!!!!2"*/$`&IW)W
@q]Fa6tL=ZBFtec@:Nt^A3t!P:gnHfATDYp!!!!$$31&+49c?f@<6*nA4(9OCh7*uBl@kp!!!!$
"98E%!"&]+!XK,5!!3Z;!!!!$$31&+49c!c@VTIaF9hjH!!*3&!!!!*!!!!$$31&+49c*d@:sIl
FEM,*#QOi)!<`B&!!!<*!!!*.!!!!]"pRhFD.7's#QOi)!<`B&!!!<*!!!*.!!!!]"r'a>EbAr[
Df]W7Bm+&ZDKKH&ATA%V!!!$&z#ljr*!t##.!'CGm6Z6dWARfgrDf,g\!!!$&z#ljr*!t##.!'CGl
9Q+ibF`9ubGmFBM!!39'!!!!2")DIn!<EK,!!!*.!!!!]"pI_>Ec>[t!!!!("98E%!"&]+!D*Uu
!!,q(!!!%%$31&,@gW29!H/;F!!.6D!=8`+!!<Q.!!#+g!!!!]#QOi)!sAT(!!!?+!!>Y%"a4<j
F_(jZ!!!*.!!!!]"q+7JDffnn@VTIaF9hjH!!*3&!!!!"!=8`+!!<Q.!!#+c#uY>EFCB'"Ch3kP
!!!*(z&I*/oBkM-t&I)``Ec,H/!=8`+!!<Q.!!#+c$:9#[AQ*kk@W-&g!!!!""98E%!!rW*!!<Q.
!!#+c%7>&NE+s-"E^FS\@qu>M!!!9-z$31&,8I>Ft!Ds1(!!-1/!!!%0$31&,D[HIE!HneM!!.WO
!=8`+!!<Q.!!#+c$UScPA7]d[FEq\6#QOi)!<`B&!!!<*!!!*.!!!!]"pS"JEbTE(#QOi)!<`B&
!!!<*!!!*.!!!!]"pS"OD.7F"#QOi)!<`B&!!!$##ljr*!t##.!'CGh:iC&cF9hjH!!<?(!!!!2
!I,1WGl[pH#ljr*!t##.!'CGu8RuCMFD5iB6tp.QBl@ltEd7oj!!!*(z$31&-#RUP3!Y5;<!!!!$
$31&+49c!VBln3#E!QFD!!*3&!!!!2%!-Q1ATD9s@<6L$EsVgH!!<Q.!!",E!!!!<#QOi).ffqV
!!!*.!!!!]$31&+8I>Ft!m1fL!!!*.!!!!]$31&,V@!;'!R1oN!!!*.!!!!]$31&,bmFFN!tYb=
!!!*.!!!!]$31&+JI2AW!fmWf!!!*.!!!!]$31&-?O?c5!tYb=!!!*.!!!!]$31&-apJ+K!ilV-
!!!*.!!!!]$31&-NsYje"1AL9!!!*.!!!!]$31&+AdSM<!N$/'!!!*.!!!!]$31&++:8)K!ac66
!!!*.!!!!]$31&,0+%[Z"=XWW!!!*.!!!!]$31&-WsSh,!fmWf!!!*.!!!!]$31&-+:8)K!fmWf
!!!*.!!!!]$31&-jpD(g!(dIs!!!*.!!!!]$31&.&./C;!fmWf!!!*.!!!!]$31&.0F@d[!il>&
#ljr*!t##.!'CSg!!?7/!!!(]!<EK,!!!*.!!!!]$31&+4:2&g"#(#]!!!*.!!!!]$31&.[LiUZ
Bl!eN#ljr*!t##.!'CSg!!Cm]!!!(]!=8`+!!<Q.!!#+g!!!-.$31&/XpG(.!!<Q.!!#+g!!!-N
$31&.<WN4-!!!!$$31&+4:2&g"E=bK!!82f!!!!$$31&+4:2&g"Hj)l!!/r'!!!!$$31&+4:2&g
"Ki(3!!JGc!=8`+!!<Q.!!#+g!!!/G$31&-Nr]7^#ljr*!t##.!'CSg!!Mcu!!!!A!=8`+!!<Q.
!!#+g!!!0I$31&,V?m5&!!ru4!!+_`%%ndT^e+V5z!=8`+!!EW/!!48G!!!-$"98E%+:E](!=/W)
!<3?*!!!E7!!!"M!s/Q*!<E9'!<EK,!!!*.!!!/k"98E%!sel,!!NB0!!!!$$31&+49c6]<)Q&!
De!QWDe*Eq$31&2K*_MX!!<Q.!!#+c$Y"$pA7]d[FEq\6#ljr*!=Af,"E=_J!!!*.!!!!]"qboj
B5V-o6Z6j[ARfgrDf0V&!!!!$$31&++9VZE!!!9)!!!0'!<E3%!<s*(@<-0qH!aoSG%G];Bk;Jh
+Unk~>;. 
	grammar := anObject.