as yet unclassified
example5

	^ #V2;BTRImageMorph;A58;Image1;<~M,6r;%14!\!!!!.8Ou6I!!!!;!!!!;#R18/!3&Rac2[hLkt+9/<-V_D<dTc?obF(mHfiW/pV$I^
Z7NTqm'=eun$3H>A=$ReUaRl.&k]5`2"=G>MA39#'dut>7VSOGVJ3*Me5f0u2GHn]S(^mp<X"Gd
Ma4CRMkpUiiTp4WpnN>/biI'nn!ri.htbQ_>i3BEn/uoAhLU)>p`:L1]cHia=GOp<r@T.:GW-[j
p^u;mjq^X/.AN-07b19W1-ANh=\KlDLN6$0g7!>lEp4K)o:tL<kMNt-dDPG5o[jC.G%;;"5PbL)
T)&_Uj&fErpj2:Vp8<0#L\pSVekN[OY1p2[hRi<;Fa%8+mf4hY(!n38[ULK.4;a4oLM&RPSMZLd
,!nMP$)L3q[cf&Shm*Wnr:Z2]Hia$7m!4!Xks\.\Z`h3sDS63LmbNMtpM\!Z+4u7kS(;)pcn+7!
)(:XTf+-`,!L"BT'amSt6Ga$OMhJYD8^`_m(SUDf\50"0Qoq>c1]%E^o>088s7CAof&(Hp[XE3A
*rX@o/@p!WVKY^$A&C^E6n1hB<7uf=&;Or!*T'L`+@=IT(lf+uetAHA1s:TlU.iac@=$",.Sr38
$HaCfOD\9D1DUE/UUP@aP*QF3dUDGKCst^#8eY2N<6aRAApfF%LQGIEP+qO(K,^\L.9>st'/HQ:
Lg8NdpaX#*<ISF)+g%,]*?#9M#W3&$&YqS(*$`je8;BZL7!4CT`O&1)8JEe!RkuQLO]X=^8RWdF
."^pB+ej&^3]d*KKmBu>65L%=+DY-LGdsq,#l1/H9C.QA4[u/5k)6h0`hB>WS3YII(^>n\<LE]t
gsq2G(G/"$HS=sc&f**)L;1EA(e^3s\l.JArdH+l'coRtR7s8.8;lpapjs:QXf,:U,La#08kh[(
CWQif*PS[Sju(eqmN.<.4bf_M]o1eGqIPU+4,'<qIi_BJ^(6eS60`9T)PaO)/9#E=9VNpB<)GXh
M/!ITKu6Bl\d;/rO`FE#6mcY(*bMfU_0#k9fX^Mnr;5P'nG*7CGN[S_D=b5U:&cc'baD61c\#2f
cU/F1&P-#p`2fOueZ>-!&M==<d>So^7*=fc5.^%f(hfqf^m$t('11J21*-8dm`+*hgJCt6_jhTm
=>4r*h!:9gG"A#LN"_Si6-^ojKtK3pN5^`XP]U:n0tdT$NUp0B2\^7!:Hb#iW5F4I/:)&1gqKL)
O)J0ZcFPQ\-"3aUPG?Q`^e8WGKLce+SsTJT9HutU<Ff$FQ=:uQ+sN;0UduCJ'gkB/@rEr"c)AIF
3W]^IkucA@`0-OrW:D7Ae`TbHY!_Tdb4poGC6dj>M67aOAX]9J9iq,:ibZ+3)_T<)ZBt]W2+A3j
f*,:1RD[2(!nK!&_s63#=?SDOX62F8X$/p=-)kKRob0s%R)l*g8qIi)&q/^9n5+aY@Mq($C/gkK
%lC"X:c.uVW*jqZL&"FdQF/*F]IUjc#HKQ,lsT'C$#>n$U1LumS1i>!-!57!_+YDN+^+>d$?R>h
``F`eC/YO-AV.A'@q&oi7U)^AOXUl[m*9*@3PscV#<-a9Y\%bt(6Qb%E\1p%6IM1`M,N,Q0cho`
e#slL8X[i[R&%g!]a098`3XiQ5]nPCI5X>`dDOo'$s*"eYc=m_KrlNp-G!=3dsqK3B,JKkWj?F7
[M.-Ig!u!.TDC8ff@2dQ&s6G$Jmko#O_:F=QU=K@Luu9pF>l.P\%*P9R`8jAV$b*lH-C$ITY#b:
MZ+Gh82XX"-4fj1JF&Y:SCE-b)n+\2o3Y<&4B,bL$sm6"8pI4l9^&6N/>B:H_o:2c^@i$h^StnM
+,?hl$mt'fPX66'$hPjC[$-0<dS(r+fru+'RDS<YF)h!BGCdr1]N#lF5S>H=CNB\r-4]6L):(er
Q!qO%e5fPD3_cMqN-K$T9F7.SU@G3\d:]_fMWkb3%Zh#JE8VNci6oTf3-43j,q`PI",8L.K-@7:
A-IN:"C]??e=eiQ*[]Yc7`"hH9bbYDj+msSp?:5=O[*P`0.GY5P:-?\F6Cj-m+HkcFgQ=sY_3[G
D(8SnbmtiOgC,g@#*gURPkA-8_A?K5iG``"RKAE80*^8,,#"E[Jcj?6(t3WujCql5F:eLS\JO@8
q5JTBBO[n/@)9Co6Nr)2W]TF?7Al'%:p,h15U'.+V=>5YNSE#j`h"ROiQXaY@.`(g/tDqMT7$P[
rpluEo/RO0d55F'V\h&F"sMT=P4BBkT&Qbn8=rEq]MIS$bkK',[J@Q\N)Hn4bKd8.4T3KQ*'ZWA
s8M1$E9Rb#5&hQ4rr**Cg:i8Mn5:rra<k`.^e@dI;6$?$@_)_;3r:4._mDP/BJ3]HMTGo4.>6q*
<o<fi]^XoR(`OF3f^Vh/3;+CWrnnKN*dShgmb^:eRnQ4&(S'DBRH;R,lB.45m5RsRS+.]HAg7):
*Rgdgl'\Oaatj7le_A^7fjF^c0>I&_]_0S)3-FM7S3?I>S9XK.Ie*G#=>Fe))TNT>:m'_JpB(-#
!m5onR+BuO67.Ui^dUc8-[e&tjCCZBjM.EW.Z*,"(Llug47TWZ0B(0NUNlJ)6[8:3^Z+1fK@mGW
.on90K&N+\k\4m#.?d$5d?-:$r"#c`#"-)%oFM!&!!#SZ:.26O@"J~>;