defaults
defaultForm

	^ #V2;BTRImageModel;5AE;Constant2;Dictionary;14;1;((Dictionary new));Form;577;Form1;<~M,6r;%14!\!!!!.8Ou6I!!!!;!!!!9#R18/!9Ab!`;fl@'1kSX<-V`OQ<e/D<><L:@qTsDfo9mB
pu%@i-h5$^U*2CF[YRPW*tU_i=R^)bZ+?e"G1i9T9.=S<C5e!-MP/lpWVD#tPs0:9%j@&>6O@M(
G+6i(7[c.\q_:/SqtJn!AF.<HG?_cMBBIL03PTq/4nmajWjV!Ok,1%1)l]^S`^ZQs023-LL$*aV
6k@AfQL];\BSuN1D*&74KBMJ#VXEm?+uPaN"H3+\alI[O\FE9A'\ZIt5U5/T(RbZtMQ3[a8u5En
+QF56Z/ZRd8Za7,KgBnNLbb+p#DM@18:ABYnrp.CMX`O7V42tO/F'&/\o_&K!1b+kGnGOcO3oc,
<R.nSiXq:fH/o)?DodACTt)2`4='gk<E[>!`+)LSOc`:GpK<VG+jl.@?%d&5:6Z]<J<l&84i^r,
6oHE&g$`LV,0c:^)2*\,,9qZl[BL/`.KaLArR-1ceuN>nk2A8M9QLLl/M4Vj7[!8^A0dnb9,)sH
s+8,HnB5[p5.u2l;L%KGk:q>OCWr@H%Q?ToJ^+XI$sKL,54dkR:h!/.\$r!k'L`lOGW#U()'oX5
>+bijhloKVI,3t*6%rtT7DjdrY*D:hgP29@@ckU+!f:$A4]q2n0ZY'R>UM92WY6Zq\dlV/^g(71
S6\D"bThK,YR=oCV[ERMdEs^GJO""&O5BEJdcS4tGT+/q47C<Wm"UL7o5s&]'.*X][9A"G<ES&`
=(Y>r?>(`U9s_/_4QQ@;)5M0OWh_]X)+>K#C)g1EnJ#&11I;ff/!sBp(!GdTV^SVZ`%WTL<(-IE
MRU[2(4@P$"QT#f>8u!o&sdC#K36fpUlep2iWL_W6RJ":Me&sD+7M@S9p3LF3hppmeho<BmJ,hu
YFaE=,Is.59ct9<+:u=ON<.9'0T84oVm2U-W@2AbE8a/(Hg+*a5ZtR[M=sepI6Cb<>DH[mfRn'a
W2lu2jRmi^3/T7d-fD]M(!qjdOdk]Y1dCgKDN'#%p+nqILW.Y:Yrq_DEYj(b-/7J=IG!MTo1AMW
-u8rjOsK;bXU8hk`sJ,/%AGQ($fbD4b]LTENqUe]2kP0gL"T8;dE%@ggeDqoV.\8jcmMR3o"n];
b#^We3a"iY'14INqdE_m"nV#kNp$b"d^A!"lZ9sO[L!#'ks=L#ELFZ>&FS1L("C2d?Mo)aM8i*\
r<&eBi^C01cX$R<U(dq+(kDl`cdO7Mbk<0"?scoqdi.W]rY4kN&cFcnQ"6]4dEDp+mjR!Z;>8M(
VO@;'5lsk\h&QhCW9Kp?QK=._c+C\dhgPWAo^S@bm:m_Ua+DY#]>*JMPZU'InEoY=80ft#S\Mo?
H4n$[/BJaEz8OZBBY!QNJ~>;;