as yet unclassified
invertDirection

	self direction: self direction * #V3;<~"98E%":+u-!!ElE@r,RpF!,OGEckl6F`M%"!!!!$"q!b4@ruF'DIIR2"98E%&I8@:!#GqA!!!**
$UJiTDe!KiFD5Z2"p[_;FCf)rEX2XF!!*3&!!!!*!!!!$$31&+3sGmfH#7#/C^:"@!!*3&!!!!"
!=8`+!!<Q.!!#(b##fVaBl7Ph!!!!""98E%!!*B+!!!*.!!!!\"qa.AEaa6)A4(9OCh7*uBl@kp
!!!!""98E%!!**,!!!!$$31&+3sH!c@:sIlFEM,*#QOi)!<`B&!!!<*!!!*.!!!!\"pIhABl8"u
!!!!$"98E%!"f6V&HR.`!!!!$$31&+3sH!hARfgjDJ*cs#QOi)!sAT(!!!T8DfTQ)Bl4Le@rHC*
ATA(W!!!*.!!!!\"r:-KEHPi1@qB(XCh5tPCi!ZmFD5Z2#QOi)!<`B&!!!<*!!!*.!!!!\"r'a>
EbAr[Df]W7Bm+&ZDKKH&ATA%V!!!$&z#ljr*!t##.!':Ap6<$iXF_tT!E_UI_AS_VP!!!9-z&J8M]
@q]Fa;flquAQ*\kBl7Pq$u^0#B5)6lCfFtjF:ee%Bk;KV@<>oi"a4<jF_)-nD/!m%D09\r@;L't
&I`MbG\M#;D,t(]F_)-iEHP]-FEMF,!!!!$$31&+3sH$YH$!UrH#7#/C^:"@!!*3&!!!!*!!!!$
$31&+3sGmb@VTIaF9hjH!!*3&!!!!*!!!!$$31&+3sH$ZDes6$@ruF'D?p4B!!*3&!!!!*!!!!$
$31&+3sH6_<)Q)%DKBo.DKJTkA7]Q_!!!!&"98E%!"&]+!N6>*!!0\=!!!&A$31&,dfBaT!!!*.
!!!!\"q+7JDffnn@VTIaF9hjH!!*3&!!!!*!!!!$$31&+3sGmaF_tT!EX2XF!!*3&!!!!*!!!!$
$31&+3sHEd<)Q"kF*)G2@rt%RDe!QWDe*Eq#QOi)"9\])!!!?+!!0#*!!!&3$31&,aUnr&F`:o4
@r,RpF(KD!!!!!$$31&++9VZE!"fJ:!!!fA!!!!$$31&+3skrf!([Fs!!9tC!!!!$$31&+3skrf
!o41`!!4SM!=8`+!!<Q.!!#(f!!!"O$31&+TE,?!!!!*.!!!!\$31&+TF(Z!!B:)\#ljr*!t##.
!':Mf!!(+J!!!'L#ljr*!t##.!':Mf!!,%d!!!'h#ljr*!t##.!':Mf!!)3i!!!'L#ljr*!t##.
!':Mf!!*B5!!!'L#ljr*!t##.!':Mf!!-U;!!!!i#ljr*!t##.!':Mf!!/)e!!!(3#ljr*!t##.
!':Mf!!3H6!!!"1#ljr*!t##.!':Mf!!4SV!!!(n#ljr*!t##.!':Mf!!5Rr!!!'L#ljr*!t##.
!':Mf!!6^=!!!)V!=8`+!!<Q.!!#(f!!!(n&HcobC^C(A!!<Q.!!#(f!!!):$31&+aU%qI!!<Q.
!!#(f!!!"1$31&+K*_MX!!io3!!/)\!<E?'s8W*%s8W+h"98E%!!E9%!!*~>