initialization
initialize

	super initialize.
	self initializeStyle.
	self isJumping: #V3;<~"98E%":+u-!!ElE@r,RpF!,OGEckl6F`M%"!!!!$"q!b4@ruF'DIIR2"98E%'F4[=!%S'V!!!!$
"q*_<F)PQ&@<?4%D?^>;DKKH&ATA%V!!!$&z#ljr*!t##.!'CGt6#q!SH"CMRDes6$@ruF'D?p4B
!!*3&!!!!*!!!!$$31&+49cR"AT;j(DI[6d@VfUCDes6$@ruF'D?p4B!!*3&!!!!*!!!!$$31&+
49bsTEcPT6#QOi)!<`B&!!!<*!!!*.!!!!]"qX=6F(f,q6Z6dWARfgrDf,g\!!!*(z&I!8bCi"A/
"^uFl@<i.Z!!!*.!!!!]"pRk4C1Ums#QOi)!<`B&!!!<*!!!*.!!!!]"qO%";F5;?Ch7$m9lFQR
C^:"@!!NK*!!!!2&S#6ZBOt^QFDl22;fm%oDJ'OiDfTQ)Bl7?q<+U;r&I<PoATpONFC>abG%#30
AI/>:!!<Q.!!#+g!!!!A#QOi)!sAT(!!!?+!!)Kq!!!#n#ljr*!t##.!'CGi:3CD_ATA%V!!!$&
z!=8`+!!<Q.!!#+c#u+i@DJ=38A7Z#H!!!$&z!=8`+!!<Q.!!#+c'MMqUB4XnXF(o`1G%F6_FCf)r
EX2XF!!*3&!!!!*!!!!$$31&+49c-[Des6$@ruF'D?p4B!!*3&!!!!"!<E3%!=8`+!!<Q.!!#+c
$W(k^FDjraC1Ums#QOi)!<`B&!!!$#!=8`+!!<Q.!!#+c#uY>EFCB'"Ch3kP!!!*(z&I*/oBkM-t
&I)``Ec,H/#ljr*!t##.!'CGs6<$iMDf0W<@;^0]De*Eq#QOi)"U"f*!!!?+!!,:k!!!$t$31&,
?jZl6!GVo@!!!*.!!!!]"q!\BFCeBrD.7F"#QOi)!<`B&!!!<*!!!*.!!!!]"r0I(;F+c5FE1f"
F@'e^@r"eWA7]Q_!!!!%"98E%!"&]+!C$nk!!,t)!!!%-!<EK,!!!*.!!!!]"pS"OD.7F"#QOi)
!<`B&!!!<*!!!*.!!!!]"pS"JEbTE(#QOi)!<`B&!!!$#!=8`+!!<Q.!!#+c"]0,ODKH-a!!!*(
z&HR+g!I4\H!<E3%&I``'E+O'"CghC+ATJ.X!!!*.!!!!A"98E%'F4[=!%S'V!!!!$$31&+4:2&g
!(dLt!!/Yt!!!!$$31&+4:2&g!+lQ<!!%ub!!!!$$31&+4:2&g!0%<c!!3<1!!!!$$31&+4:2&g
!7V>U!!3<1!!!!$$31&+4:2&g!=0#4!!4YW!!!!$$31&+4:2&g!4`F:!!$U;!!!!$$31&+4:2&g
!@/!P!!7TU!!!!$$31&+4:2&g!$DUK!!(LT!!!!$$31&+4:2&g!M0Vu!!0\4#ljr*!t##.!'CSg
!!0\=!!!$*!=8`+!!<Q.!!#+g!!!&S$31&+8I5@s!!<Q.!!#+g!!!'($31&,#QXr,!<E3-!!!!$
$31&+4:2&g!\4ibDJ<nf!<EK,!!!*.!!!!]$31&-:C7(%!=/u3!!!*.!!!!]$31&-IL6&T!n[eZ
!!!*.!!!!]$31&-\-`39!u)%A!!!*.!!!!]$31&-fEqTY!=/],#ljr*!t##.!'CSg!!<oB!!!*T
#ljr*!t##.!'CSg!!=n^!!!"2!<E3-!!!!$$31&+4:2&g"&B7(!!*?+!<E3%!=8`+!!N]0!!+>G
!=8`+!!<Q.!!",Ez#QOi)"T\W)!<E6~>.
	self velocity: #V3;<~"98E%":+u-!!ElE@r,RpF!,OGEckl6F`M%"!!!!$"q!b4@ruF'DIIR2"98E%&I8@:!#GqA!!!**
$UJiTDe!KiFD5Z2"p[_;FCf)rEX2XF!!*3&!!!!*!!!!$$31&+3sGmfH#7#/C^:"@!!*3&!!!!"
!=8`+!!<Q.!!#(b##fVaBl7Ph!!!!""98E%!!*B+!!!*.!!!!\"qa.AEaa6)A4(9OCh7*uBl@kp
!!!!""98E%!!**,!!!!$$31&+3sH!c@:sIlFEM,*#QOi)!<`B&!!!<*!!!*.!!!!\"pIhABl8"u
!!!!$"98E%!"f6V&HR.`!!!!$$31&+3sH!hARfgjDJ*cs#QOi)!sAT(!!!T8DfTQ)Bl4Le@rHC*
ATA(W!!!*.!!!!\"r:-KEHPi1@qB(XCh5tPCi!ZmFD5Z2#QOi)!<`B&!!!<*!!!*.!!!!\"r'a>
EbAr[Df]W7Bm+&ZDKKH&ATA%V!!!$&z#ljr*!t##.!':Ap6<$iXF_tT!E_UI_AS_VP!!!9-z&J8M]
@q]Fa;flquAQ*\kBl7Pq$u^0#B5)6lCfFtjF:ee%Bk;KV@<>oi"a4<jF_)-nD/!m%D09\r@;L't
&I`MbG\M#;D,t(]F_)-iEHP]-FEMF,!!!!$$31&+3sH$YH$!UrH#7#/C^:"@!!*3&!!!!*!!!!$
$31&+3sGmb@VTIaF9hjH!!*3&!!!!*!!!!$$31&+3sH$ZDes6$@ruF'D?p4B!!*3&!!!!*!!!!$
$31&+3sH6_<)Q)%DKBo.DKJTkA7]Q_!!!!&"98E%!"&]+!N6>*!!0\=!!!&A$31&,dfBaT!!!*.
!!!!\"q+7JDffnn@VTIaF9hjH!!*3&!!!!*!!!!$$31&+3sGmaF_tT!EX2XF!!*3&!!!!*!!!!$
$31&+3sHEd<)Q"kF*)G2@rt%RDe!QWDe*Eq#QOi)"9\])!!!?+!!0#*!!!&3$31&,aUnr&F`:o4
@r,RpF(KD!!!!!$$31&++9VZE!"fJ:!!!fA!!!!$$31&+3skrf!([Fs!!9tC!!!!$$31&+3skrf
!o41`!!4SM!=8`+!!<Q.!!#(f!!!"O$31&+TE,?!!!!*.!!!!\$31&+TF(Z!!B:)\#ljr*!t##.
!':Mf!!(+J!!!'L#ljr*!t##.!':Mf!!,%d!!!'h#ljr*!t##.!':Mf!!)3i!!!'L#ljr*!t##.
!':Mf!!*B5!!!'L#ljr*!t##.!':Mf!!-U;!!!!i#ljr*!t##.!':Mf!!/)e!!!(3#ljr*!t##.
!':Mf!!3H6!!!"1#ljr*!t##.!':Mf!!4SV!!!(n#ljr*!t##.!':Mf!!5Rr!!!'L#ljr*!t##.
!':Mf!!6^=!!!)V!=8`+!!<Q.!!#(f!!!(n&HcobC^C(A!!<Q.!!#(f!!!):$31&+aU%qI!!<Q.
!!#(f!!!"1$31&+K*_MX!!io3!!/)\!<E<'!!!!%z"98E%A-;l4!!*~> @ #V3;<~"98E%":+u-!!ElE@r,RpF!,OGEckl6F`M%"!!!!$"q!b4@ruF'DIIR2"98E%&I8@:!#GqA!!!**
$UJiTDe!KiFD5Z2"p[_;FCf)rEX2XF!!*3&!!!!*!!!!$$31&+3sGmfH#7#/C^:"@!!*3&!!!!"
!=8`+!!<Q.!!#(b##fVaBl7Ph!!!!""98E%!!*B+!!!*.!!!!\"qa.AEaa6)A4(9OCh7*uBl@kp
!!!!""98E%!!**,!!!!$$31&+3sH!c@:sIlFEM,*#QOi)!<`B&!!!<*!!!*.!!!!\"pIhABl8"u
!!!!$"98E%!"f6V&HR.`!!!!$$31&+3sH!hARfgjDJ*cs#QOi)!sAT(!!!T8DfTQ)Bl4Le@rHC*
ATA(W!!!*.!!!!\"r:-KEHPi1@qB(XCh5tPCi!ZmFD5Z2#QOi)!<`B&!!!<*!!!*.!!!!\"r'a>
EbAr[Df]W7Bm+&ZDKKH&ATA%V!!!$&z#ljr*!t##.!':Ap6<$iXF_tT!E_UI_AS_VP!!!9-z&J8M]
@q]Fa;flquAQ*\kBl7Pq$u^0#B5)6lCfFtjF:ee%Bk;KV@<>oi"a4<jF_)-nD/!m%D09\r@;L't
&I`MbG\M#;D,t(]F_)-iEHP]-FEMF,!!!!$$31&+3sH$YH$!UrH#7#/C^:"@!!*3&!!!!*!!!!$
$31&+3sGmb@VTIaF9hjH!!*3&!!!!*!!!!$$31&+3sH$ZDes6$@ruF'D?p4B!!*3&!!!!*!!!!$
$31&+3sH6_<)Q)%DKBo.DKJTkA7]Q_!!!!&"98E%!"&]+!N6>*!!0\=!!!&A$31&,dfBaT!!!*.
!!!!\"q+7JDffnn@VTIaF9hjH!!*3&!!!!*!!!!$$31&+3sGmaF_tT!EX2XF!!*3&!!!!*!!!!$
$31&+3sHEd<)Q"kF*)G2@rt%RDe!QWDe*Eq#QOi)"9\])!!!?+!!0#*!!!&3$31&,aUnr&F`:o4
@r,RpF(KD!!!!!$$31&++9VZE!"fJ:!!!fA!!!!$$31&+3skrf!([Fs!!9tC!!!!$$31&+3skrf
!o41`!!4SM!=8`+!!<Q.!!#(f!!!"O$31&+TE,?!!!!*.!!!!\$31&+TF(Z!!B:)\#ljr*!t##.
!':Mf!!(+J!!!'L#ljr*!t##.!':Mf!!,%d!!!'h#ljr*!t##.!':Mf!!)3i!!!'L#ljr*!t##.
!':Mf!!*B5!!!'L#ljr*!t##.!':Mf!!-U;!!!!i#ljr*!t##.!':Mf!!/)e!!!(3#ljr*!t##.
!':Mf!!3H6!!!"1#ljr*!t##.!':Mf!!4SV!!!(n#ljr*!t##.!':Mf!!5Rr!!!'L#ljr*!t##.
!':Mf!!6^=!!!)V!=8`+!!<Q.!!#(f!!!(n&HcobC^C(A!!<Q.!!#(f!!!):$31&+aU%qI!!<Q.
!!#(f!!!"1$31&+K*_MX!!io3!!/)\!<E<'!!!!%z"98E%A-;l4!!*~>.