as yet unclassified
qwertz
	
	<BTRConstantMethod>
	^ (Morph basicNew instVarNamed: #bounds put: (901@412 corner: 951@452);
instVarNamed: #submorphs put: Array empty;
 instVarNamed: #fullBounds put: (901@412 corner: 951@452);
 instVarNamed: #color put: (Color r: 0.0 g: 1 b: 0.502);
 instVarNamed: #extension put: (MorphExtension basicNew instVarAt: 1 put: false; instVarAt: 2 put: true; instVarAt: 3 put: false; instVarAt: 4 put: nil; instVarAt: 5 put: nil; instVarAt: 6 put: nil; instVarAt: 7 put: false; instVarAt: 8 put: nil; instVarAt: 9 put: nil; instVarAt: 10 put: nil; instVarAt: 11 put: ((IdentityDictionary new) add: (#animations->((OrderedCollection new))); add: (#borderStyle->(BorderStyle basicNew yourself)); add: (#signalConnections->((Dictionary new))); yourself); yourself);
 yourself)