collision
collideWith: aBMGameObject info: aBMCollisionEvent
	
	aBMGameObject isJumping: #V3;<~"98E%":+u-!!ElE@r,RpF!,OGEckl6F`M%"!!!!$"q!b4@ruF'DIIR2"98E%'F4[=!%S'V!!!!$
"q*_<F)PQ&@<?4%D?^>;DKKH&ATA%V!!!$&z#ljr*!t##.!'CGt6#q!SH"CMRDes6$@ruF'D?p4B
!!*3&!!!!*!!!!$$31&+49cR"AT;j(DI[6d@VfUCDes6$@ruF'D?p4B!!*3&!!!!*!!!!$$31&+
49bsTEcPT6#QOi)!<`B&!!!<*!!!*.!!!!]"qX=6F(f,q6Z6dWARfgrDf,g\!!!*(z&I!8bCi"A/
"^uFl@<i.Z!!!*.!!!!]"pRk4C1Ums#QOi)!<`B&!!!<*!!!*.!!!!]"qO%";F5;?Ch7$m9lFQR
C^:"@!!NK*!!!!2&S#6ZBOt^QFDl22;fm%oDJ'OiDfTQ)Bl7?q<+U;r&I<PoATpONFC>abG%#30
AI/>:!!<Q.!!#+g!!!!A#QOi)!sAT(!!!?+!!)Kq!!!#n#ljr*!t##.!'CGi:3CD_ATA%V!!!$&
z!=8`+!!<Q.!!#+c#u+i@DJ=38A7Z#H!!!$&z!=8`+!!<Q.!!#+c'MMqUB4XnXF(o`1G%F6_FCf)r
EX2XF!!*3&!!!!*!!!!$$31&+49c-[Des6$@ruF'D?p4B!!*3&!!!!"!<E3%!=8`+!!<Q.!!#+c
$W(k^FDjraC1Ums#QOi)!<`B&!!!$#!=8`+!!<Q.!!#+c#uY>EFCB'"Ch3kP!!!*(z&I*/oBkM-t
&I)``Ec,H/#ljr*!t##.!'CGs6<$iMDf0W<@;^0]De*Eq#QOi)"U"f*!!!?+!!,:k!!!$t$31&,
?jZl6!GVo@!!!*.!!!!]"q!\BFCeBrD.7F"#QOi)!<`B&!!!<*!!!*.!!!!]"r0I(;F+c5FE1f"
F@'e^@r"eWA7]Q_!!!!%"98E%!"&]+!C$nk!!,t)!!!%-!<EK,!!!*.!!!!]"pS"OD.7F"#QOi)
!<`B&!!!<*!!!*.!!!!]"pS"JEbTE(#QOi)!<`B&!!!$#!=8`+!!<Q.!!#+c"]0,ODKH-a!!!*(
z&HR+g!I4\H!<E3%&I``'E+O'"CghC+ATJ.X!!!*.!!!!A"98E%'F4[=!%S'V!!!!$$31&+4:2&g
!(dLt!!/Yt!!!!$$31&+4:2&g!+lQ<!!%ub!!!!$$31&+4:2&g!0%<c!!3<1!!!!$$31&+4:2&g
!7V>U!!3<1!!!!$$31&+4:2&g!=0#4!!4YW!!!!$$31&+4:2&g!4`F:!!$U;!!!!$$31&+4:2&g
!@/!P!!7TU!!!!$$31&+4:2&g!$DUK!!(LT!!!!$$31&+4:2&g!M0Vu!!0\4#ljr*!t##.!'CSg
!!0\=!!!$*!=8`+!!<Q.!!#+g!!!&S$31&+8I5@s!!<Q.!!#+g!!!'($31&,#QXr,!<E3-!!!!$
$31&+4:2&g!\4ibDJ<nf!<EK,!!!*.!!!!]$31&-:C7(%!=/u3!!!*.!!!!]$31&-IL6&T!n[eZ
!!!*.!!!!]$31&-\-`39!u)%A!!!*.!!!!]$31&-fEqTY!=/],#ljr*!t##.!'CSg!!<oB!!!*T
#ljr*!t##.!'CSg!!=n^!!!"2!<E3-!!!!$$31&+4:2&g"&B7(!!*?+!<E3%!=8`+!!N]0!!+>G
!=8`+!!<Q.!!",Ez#QOi)"T\W)!<E9~>.
	aBMGameObject collideWithPlatform: self info: aBMCollisionEvent.