initialization
initializeMenuOptions
	self 
		defaultTarget: self;
		add: (self textFor: #install) action: #install icon: #V2;BTRImageModel;2A2;Constant2;UndefinedObject;5;1;nil;UndefinedObject;5;1;nil;Form;25E;Form1;<~M,6r;%14!\!!!!.8Ou6I!!!!1!!!!1#R18/!$Ch4@/p9.Sk2=9<-V`OPM8\2;&"b5O'X!pVTT>8
l2cJjW/Kl:Ms(0kTd'[TMA[+>.AkX;Z@c,@*CdjN%BM5u4!05/SXI>&LHkO19H,RB2LHJ;>6"Gd
4g5Yab\4'"?rn-RfU<1*[_CaPV;igLf@]*5_q*S>EFUp-74o8hH@&rXRU<1>hpq.b$_@q(#2d<K
)#jutk4bZDrIWNVdo)9+5W8Rm*?@MBW#;*ofn]aQ0c#Zp*5)"iWhp<STJ]*7f489p9HYW8=O#oW
LSnpXhJuGrq`q<hE>F9(n/h8"D-V$WUbB'npa);<N"AF?_F5Nn^ZM5A?M5!YcP9'[/(culd(]!8
L4C7g6(gU0&:nRV+KGmlX@s1``=T]Oe%jJT'A=IX'V/Go=FD1Vc++>"-aPQo,*>,9&qN8pP`h+o
_Ii#"eelt41\#]p/g0oc0%gY'WMi4sRMmLj1#"o8bteWhHkV02[mEMVqd*Hi,`-,(<[RTUO\[=n
4AX'Kp^7r@-gT!7rti1MY.VgeOGEB)Z2DW)@sSA:W?5`RL!-=n!!!!j78?7R6=>B~>;;;
		add: (self textFor: #startGame) action: #startNewGame icon: #V2;BTRImageModel;292;Constant2;UndefinedObject;5;1;nil;UndefinedObject;5;1;nil;Form;24E;Form1;<~M,6r;%14!\!!!!.8Ou6I!!!!1!!!!1#R18/!$Ch4@/p9.O\%r,<-V`?P<DH';&G$p-u*I6.VNL:
M1V%ZbTEo/)B+4#4c9Z#C24-RAt,$6N@_d;C6Su=79!4c/Q$4.V,B[DfFR[umM2p3]I>kR*4Y/o
chEukF$W3e,11HS,DRVR]qTI8+ND2_=0c6$CI43J"DA/Mg,DjM.N.n#3#HUtW@eP-,RV&@6SefJ
]*J4KdB6^J`u)?Oa3"3A8W1\6)@5GK,/XU+*Gjbl&%AIHUkNF@]eo`t779GE`&`Md$.aEr@;Q8)
iD(#KUZ@AcCsa.=>^su7@Ku;-P4XjgI@&590d0u&j]I3>LcN-LNSZ*m0iP98nhh[Y[h%*Ipb6R*
lKLD:Z9NjTSs0ONnmQeJ*<P)Fmiuqr>+>-B-StSR>QjY,=Wi1KHSLZ30-,LOo<>GUjLt^R=<[0h
)cP/c%nqJd7()2/+4uH--eS8od_EStmVZ@i^qo&5Xb/r3=5_K`'7fa0<,GiB`H8-g<W<\f0la/@
nM%9ZqM[OOGBQgNEhTS%i"p[jKOFoBQ"C!r!!#SZ:.26O@"J~>;;;
		add: (self textFor: #exitGame) action: #exitGame icon: #V2;BTRImageModel;423;Constant2;UndefinedObject;5;1;nil;UndefinedObject;5;1;nil;Form;3DF;Form1;<~M,6r;%14!\!!!!.8Ou6I!!!!1!!!!1#R18/!$Ch4@/p9/c:LDi<-V`GdToCB@2K7=',4_o+X%Ia
6!+h,'kA!nI7W1J@HNPoiDo$1[\i;&P,KfCL"'_(Rh"8ORnI=A9GEV@`4=jheACZg&[Akt4`e'8
q"MKU-k.gkn3=RU_u"eQkC$\i>OWIFMZjHA!k#GD-n?g#6m@1Q,_Ai@"OD!pH^i($:&r,gDjF+H
'D69MK00GK(`=3B7\`7tI6D*r)+mOp;-[@bJq=%."9JUW66Sal&X"QZi@msoN"efn_"d[a3]]<p
<i])!=2tkUM,Ys9!*u-jo!Gi7md<5++qaJ@R43*@!EQ69h;-n#Df97oXe`P>)ANu%nG<MW>&][?
<\cI>k;[92/]+5sJlek^`W2LQ#.)tkUX=luZAMPZA<fu%bOZaHP*>Df59HTuI`u*-LtP^`E5orY
,KBs*@(4n<gY3+"aTS_H$^F><L5#oR91n,%)@qm2N*t[M"A*_Znirr!+`&i/+M%gM'>:HI$[TK-
/M/R$4tjbi.G#pY+@*qoaoh.4WSl5HJPT'3O=W0\0/,@FLn:1Z(l1j]j?8pDHK?XS=]tNFq@#9B
`5+sXXcrZ*fc_:S!t5VJYr6e"TrkU5+"20t4>rBU_b8"]TnkoX,IRa_o_%m^IF+)tl"R)2C1',K
!qQ`=n;C8P7?2?Iq@34;hLb4i*=D_$!<r`4fQ#>$6*$*jjcG:jiH*^?bg=ck-*_l<*'?nB@tN_f
@Y!8m3]fE#?="+aZO.(5$h1<GYUFq9mXUS2i:E[7V5+plp`;+O4H.\8;(.Y9B\Jn04mTtjHP,\R
's)k(A*rS3jqWkpV;0,6g+o[=Y:'t&!2n9PA#B>gI2cu4.id$%E6UB$R\cG+Q`6BE'GcNSE/;\a
RTiqc;Mq""C^>\iOIMRM'4JU_?g)]RTr<hK#<;;NYP\P?Gfgb7[r7T5!!!!j78?7R6=>B~>;;;
		add: (self textFor: #chooseLanguage) action: #changeLanguage icon: #V2;BTRImageModel;268;Constant2;UndefinedObject;5;1;nil;UndefinedObject;5;1;nil;Form;224;Form1;<~M,6r;%14!\!!!!.8Ou6I!!!!1!!!!1#R18/!$Ch4@/p9.F%Jbc<-V_Z(mKOkL_G;`1-\#'?4dd3
_a*o(+O1$t?:()j`Pofgp%ES-J,K)us*t&tr;ZfskPl>O*rhioGNOBD7>27;2'k4>X/IHHHi<di
=;*UjmG!Er()H'4JSJu)3W%RAF!ksBL1-0Z=BScmL<(MWi2E:ks8U]i1]K[_GPqKP@`eYB-]e3*
[V6bLrT!C]ru\l,s*pG$qu?+HfDdolfRXH%6oMhI6:1VMQW;6.J(qL,s,R8o_7"nOrA_))9Rgkq
qYq9Ys5W%/s5rHU+9NgL%:BD"(OPoC!,MN,lO1YQJ%qcLJUr.5`o[4o9MF>pl@mX'_+7g9m/>1u
=)e$9ji]%Oe^`3!!7cDRM?sG]:<qluVG-dbq=@g01kOp)-P$0[X/l4%9G>U#C38ql";Vc=PLlsC
r.!qWhZ%nJ\po8tH[n'UM"um!KsI;Amf-a+UON?u'1%"DP;+J#g43:i@E8EKYj*Dh;,7TPz8OZBB
Y!QNJ~>;;;
		add: (self textFor: #chooseSpecification) action: #chooseSpecification icon: #V2;BTRImageModel;16B;Constant2;UndefinedObject;5;1;nil;UndefinedObject;5;1;nil;Form;127;Form1;<~M,6r;%14!\!!!!.8Ou6I!!!!1!!!!1#R18/!$Ch4@/p9-W(BBC<-V_Zq#C@Y_g`"I7@L2gJ8tDY
)O$'Gs%1$L4`CKg!k7%aa1tL%mKR0;EZdMi%=!-Ur;X7F2.-i%P@VJBX3^d[m%"0>#%A,_,Y#-A
+<+aX@2Rf8"MI&+@l8eq&-E8o.Gf:Bir=jPHbgQ;-J<qKQEC1p`BJkCKU2#$)pm?Lk.d577kj@J
>"?.)HV^18\mc$amlbe#df>8(idbVf!1YY3K\dYqb5_MB!(fUS7'8jaJc~>;;.
