initialization
initialize
	super initialize.
	self title: 'Definitely Not Mario!';
		 chooseLanguage;
		 specification: DNMLevelSpecification default;
		 position: #V2;BTRNumberModel;51;N1;SmallInteger;3;1;0;SmallInteger;3;1;0;SmallInteger;5;1;100;SmallInteger;3;1;1;; @ (World height * #V2;BTRNumberModel;4F;N1;Fraction;5;1;3/4;SmallInteger;3;1;0;SmallInteger;5;1;100;SmallInteger;3;1;1;;);
		 stayUp: true;
		 initializeMenuOptions