as yet unclassified
setUp

	super setUp.
	self graph: #V2;BTRWrapperBlock;1E2;Wrapper1;BTRGraphModel;1C6;Smart;self referenceDictionary at: 1 put: (BTRGraphModel basicNew instVarNamed: #cachedStoreString put: nil;
 instVarNamed: #originalText put: nil;
 instVarNamed: #viewData put: nil;
 instVarNamed: #nodes put: (self referenceAt: 2);
 instVarNamed: #edges put: (self referenceAt: 3);
 yourself). 
self referenceDictionary at: 2 put: ((OrderedCollection new)). 
self referenceDictionary at: 3 put: ((OrderedCollection new)). 
self referenceDictionary at: 1;;copy.