as yet unclassified
testEdgeAdditionRequestedByNode
	
	| node1 node2 |	
	node1 := BTRGraphNode default.
	node2 := BTRGraphNode for: #V3;<~"98E%":+u-!!ElE@r,RpF!,OGEckl6F`M%"!!!!$"q!b4@ruF'DIIR2"98E%-jTeQ!)En$!!!**
$UJiTDe!KiFD5Z2"qjL<ASuU(FEp8g@ruF'DIIR2#QOi)!sAT(!!!T7FCB!%GnC3gEcPT6!=8`+
!!<Q.!!#(b&4g5NBOt^ADes6$@ruF'D?p4B!!<?(!!!!+!!!"2$31&+D$^1B!!<Q.!!#(b%74#l
6>URMCJA_fE+fLW!!!9-z&I)]_F`(`2&I!)sDImi#$$15uD/XH6BQFamAp%p+6>q!aA9/=d@rH1%
EY/UhG][M7F(oQ1&IMu`De!QWDe*Eq#ljr*!t##.!':Mf!!#(d!!!!$"98E%!"f<KAU+jkG%#30
AI/>:!!<Q.!!#(b#>&fTAS5Rp#QOi)!<`B&!!!<*!!!*.!!!!\"qXaS@;^.&F^o!#F@0t_DfQ*`
!!!0*z&Hd&d@M&uX@:Nt^A41!JFD)6t@prk\ARn,AFAQCfFCfK1&HuTZE+iYd!!!!$$31&+3sH6i
@<ld6FAR!rE+O'3Bk;>k!!!!%"98E%!"fNN;Iso`H>.80&IEVYATMR3Bl7Pq%:j0o@:F%a9OW3b
F`[oi!!!*.!!!!\"qa.AEaa6)A4(9OCh7*uBl@kp!!!!""98E%!!rW*!!<Q.!!#(b'gbkt6"4nW
Ea`I"6>URMCJA_XAS_VP!!!-)z&J8M]@q]Fa;flquAQ*\kBl7Pq$u^0#B5)6lCfFtjF:ee%Bk;KV
@<>oa!!!!$$31&+3sGmfH#7#/C^:"@!!*3&!!!!"#ljr*!t##.!':Aq6<$iaEa`p+ATC+RDe!Pg
!!!!)"98E%!"&]+!6>KI!!(@Q!!!#N$31&+iX,Yc!:C0o!!)[(%!Q`#E,]B!6>URMCB4GB!!!!$
$31&+3sGmaF_tT!EX2XF!!*3&!!!!*!!!!$$31&+3sH*lBl.g*AO:<UA7]ce!!!!%"98E%!"fNH
@<6!IDes?4&HuZ_Ci=>+"a=ZkFD(s\!!!*.!!!!\"pRD.FDYH*#QOi)!<`B&!!!$#!<E3-!!!!$
$31&+3sH-\<)Q)%Ci=>gDe*Eq#QOi)"U"f*!!!?+!!57i!!!'r$31&->nI6`@;L't!<E3-!!!!$
$31&+3sH*e@<ld6FAQmlBk)Do!!!!""98E%!!rW*!!<Q.!!#(b#u+i@DJ=38A7Z#H!!!$&z#ljr*
!t##.!':Am8T&T\F@'ndA7]ce!!!!%"98E%!"&]+!u2.C!!=>N!!!*K!<EK,!!!*.!!!!\"pI;5
Eaa5!!!!!""98E%!!rW*!!<Q.!!#(b"[d3EDfQ*`!!!-)z$31&,F:&!J!I5"P!!.fT!<E3%!=8`+
!!<Q.!!#(b(/ndaF_,H#ART%aAOCBPCh7*uBl@kp!!!!""98E%!!rW*!!<Q.!!#(b#uY>EFCB'"
Ch3kP!!!*(z&I*/oBkM-t&I)``Ec,H/!=8`+!!<Q.!!#(f!!!!A#QOi)!sAT(!!!?+!!$U<!!!"9
!=8`+!!<Q.!!#(b"\ioUE+fLW!!!6,z$31&+a9hnI!72&Q!!(UX!!!#Y$31&+mKrpo!;-?n#ljr*
!t##.!':Ap9lG&kBLR/fASuR'Df,g\!!!E1z&I*&i@r#Xd&I3JnF(o*"AJ#,fFD56#GnCEn@;Kau
Df/NcG]XN2@UX(hDf9MmAU&;qASbpfFDl13$tX[*ATDZsCeeDUAJ#>bF&6:cFE9igDJsP-$=RFd
DfScu@<?&m#&nBeH"D".$tXTnDKJEXDIdQpEY/h#FD,6+:i^JnATDm,ATJ.X!!!*.!!!!\"r'a>
EbAr[Df]W7Bm+&ZDKKH&ATA%V!!!$&z#ljr*!t##.!':Al6@!Za;fm%oDJ'4T!!!$&z!=8`+!!<Q.
!!#(b$W(k^FDjraC1Ums#QOi)!<`B&!!!$#!=8`+!!<Q.!!#(b$WLPDCh6:KH#IhI#QOi)!sAT(
!!!T<E,ol9ATDm,ATJFnD/!lVG][M7F@0JHBOqJM!!!*.!!!!\"q!_9Ci!ZmFD5Z2#QOi)!<`B&
!!!<*!!!*.!!!!\"r1*G@VfUL@<ld6FAR!rE+O'3Bk;>k!!!!2"98E%!"&]+!Q>BG!!1FR!!!&S
&IDrYChu[\F(KG*%qB0eCf#%kBln'-DJ=!$&IW)[Ci!$h@:O"hB+YMf@<ld6F@g@kATSLnCh[s4
6Y1.WATDL&B+YShBleAaBl[cpFD5Z2&IWDhF*(?"@:O"hB+Y_rAThX*F(J<Z@VfUCASc1(&J&o)
@U`nh6=FbB6Y1(MEtJk*Ea`oSASuU$EbTE(&Iir)@;nVKEb/a&Bl@l$$Z0Tq6Y1(M;e^Ph&IWGa
GXH%YCf>%oAH<);!!!*.!!!!\"q<mu;F>A=DfSQjEc>[t!!!!*"98E%!"&]+!6>KI!!(@Q!!!#N
$31&+iX,Yc!:C0o!!)[!!!!$"&J/GjCi=>mFE2)5B2*;bE+fOX!!!*.!!!!\"pmtADejK794`AS
!!!!#"98E%!"&]+!@8$P!!!*.!!!!\"q*b9Eb&a%;fm;$AI&89!!*3&!!!!*!!!!$$31&+3sH'k
FE2)5B2*;bE+fLW!!!B0z$31&+a9hnI!72&Q!!(UX!!!#Y$31&+mKrpo!;-p,AoDR/&I;rbE+i[$
Blajl@rH7,ASuU2&I<&YF%1(XF`RQa#ljr*!t##.!':Al6@!Za;gE4hDeo[Z!!!$&z#ljr*!t##.
!':Ar6<$iMDf0W<@;^0]De*Eq#QOi)"U"f*!!!?+!!57i!!!'r$31&->m^Q3"+^IR!<EK,!!!*.
!!!!\"pS"JEbTE(#QOi)!<`B&!!!$##ljr*!t##.!':Ah:L\'M@rqtV!!!$&z!=8`+!!<Q.!!#(b
"]0,ODKH-a!!!*(z&HR+g!I4\X%!-Q1ATD9s@<6L$EsVgH!!<Q.!!",E!!!!I#QOi):C."$!!<Q.
!!#(f!!!!i$31&++9;cK!!!*.!!!!\$31&+Y6k70"OdYW!!!*.!!!!\$31&+IgQ/U#&";C!!!*.
!!!!\$31&+3skrf#M9=_!!!*.!!!!\$31&,3skrf!oXFc!!!*.!!!!\$31&-)[ZQF#lY,1!!!*.
!!!!\$31&,W<rV*#lY,1!!!*.!!!!\$31&,oEkQu"B,U,!!!*.!!!!\$31&-E=)[G#iH!h!!!*.
!!!!\$31&,=:,$."=!pR!!!!$$31&+3skrf!fdTf!!LaO!=8`+!!<Q.!!#(f!!!)Z$31&.[g<$7
!!<Q.!!#(f!!!*!$31&2r!<?'!!<Q.!!#(f!!!*\$31&,oDnsn!<EK,!!!*.!!!!\$31&.=UG-/
#bh>#!=8`+!!<Q.!!#(f!!!+d$31&3rWrQ)!!<Q.!!#(f!!!,1$31&3rWrQ)!!<Q.!!#(f!!!,P
$31&-r;cp*!!!!$$31&+3skrf":,>7!!2]u!!!!$$31&+3skrf"="6R!!rQ)!<E3%!=8`+!!<Q.
!!#(f!!!.#$31&1BF+Y=!!<Q.!!#(f!!!.O$31&3rW*<*!!!*.!!!!\$31&++:8)K!.P"U!!!!$
$31&+3skrf"Od\X!!rQ)!=8`+!!<Q.!!#(f!!!04$31&3rWrQ)!!<Q.!!#(f!!!28$31&,3sble
!!<Q.!!#(f!!!2b$31&3huO,a!!!*.!!!!\$31&1#8%&UBl!eN!=8`+!!<Q.!!#(f!!!3R$31&.
PmIEj!!<Q.!!#(f!!!4:$31&3rWrQ)!!<Q.!!#(f!!!4Z$31&,W<!;*!!!*.!!!!\$31&2J-l8V
!3Z\/!!!*.!!!!\$31&2fEqTY"1JR:!!!*.!!!!\$31&2r!EE(#lY,1!!!*.!!!!\$31&3*=;cH
"OdAP#ljr*!t##.!':Mf!!n/`!!!(?#ljr*!t##.!':Mf!!o;+!!!'>!<E3%#ljr*!t##.!':Mf
!!qKi!!!&l!<EK,!!!*.!!!!\$31&3rX&W*"pY/8!!!!$$31&+3skrf#oa3O!!rQ)#ljr*#RUP3
!fdck!!!.p%KQh8!!!$+!!!!*$31&2J.DV[!!Jr)$31&7S-T)p!!*B+!!!B6!!!9F%fh[k":u%M
!!!G6#QOi)!!*B+!!!-/!!!-H"98E%!!E9%!$DZ""p"u/!!!$+!!!!-$31&0%Kcb7!<E3'!<E3-
!!!!$$31&+8-Anm!!3E+!!!0/!!!!$$31&+3sH:<BkM<lCdW,YDIm="Bl@m1#ljr*!t##.!$DCE
!!!!)!!!!&!<E3%!<EK,!!!*.!!!!\"q+mYEb&a%;fm;$AI/>:!!*E,!!iE&!<E<'!!!!2#9toV
7Rf?k!s&].!!!-/!!!-H"98u3!W`<.!!!!-$31&0%Kcb7!<E3'!<E3-!!!!$$31&+8-Anm!!<K,
!!!0/!!!!$$31&+3skrf%64^p!!!*.!!!!A"98E%!!iQ)!!NB(!<E3%#ljr*!t##.!':Mf!"ElS
!!!IV#ljr*!t##.!':Am@rHC*ATC^kH#.$r#BFa*DId<h!=8`+!!N]0!!?@)!=8`+!!<Q.!!",E
z#QOi)"T\W)!<EN-!"GA(!!!GQ!=8`+!!N]0!!-1)z!<E<'!!!!*!!!!-$31&0%Kcb7!<E3'!<E3-
!!!!$$31&+8-Anm!!EQ-!!!B-#ljr*!t##.!':Mf!"Cpp!!!!$$31&++9VZE!!!9)!!!0'!<E3%
#ljr*!t##.!':AnCghU-F`^GuCh[C)#ljr*!t##."tK]T!<E3%!=8`+!!<Q.!!#(f!!!II#ljr*
":>,/"4deZ!"NEE!!!L;"98E%"T\o0!!!*.!!!!\"qYTZH#IhI:i^JnATDm,ATJ.X!!!T<!!!4Z
"q#EbEbTE,=)q_g$31&:5Q_,h!!!!'#%M4^FCfIs"E&-qAHVu5!!3?0FDl+lAS-#g$Zp<+<,Y*A
FEDG<$31&:?NUB;!!!OE$31&:?N^?/!!!-ds8W*+!!!K`~>.
	self graph addNode: node1.
	self graph addNode: node2.
	
	[node1 addEdge] valueSupplyingAnswer: 
		(Smalltalk version <= 'Squeak5.2'
			ifTrue: [1]
			ifFalse: [node2]).
	
	self assert: (self graph edges includes: node1 -> node2).
	