as yet unclassified
xyz
 (Morph basicNew instVarNamed: #bounds put: (0@0 corner: 50@40);
instVarNamed: #submorphs put: Array empty;
	addMorph: (Morph basicNew instVarNamed: #bounds put: (0@0 corner: 50@40);
instVarNamed: #submorphs put: Array empty;
 instVarNamed: #fullBounds put: nil;
 instVarNamed: #color put: (Color r: 0.0 g: 0.0 b: 1);
 instVarNamed: #extension put: nil;
 yourself);
 instVarNamed: #fullBounds put: nil;
 instVarNamed: #color put: (Color r: 1 g: 0.0 b: 0.0);
 instVarNamed: #extension put: (MorphExtension basicNew instVarAt: 1 put: false; instVarAt: 2 put: true; instVarAt: 3 put: false; instVarAt: 4 put: nil; instVarAt: 5 put: nil; instVarAt: 6 put: nil; instVarAt: 7 put: false; instVarAt: 8 put: nil; instVarAt: 9 put: nil; instVarAt: 10 put: nil; instVarAt: 11 put: ((IdentityDictionary new) add: (#borderStyle->(BorderStyle basicNew yourself)); yourself); yourself);
 yourself)