initialization
initializeStyle

	self
		width: (World width / #V2;BTRNumberModel;1D;Constant1;SmallInteger;3;1;2;;);
		height: #V2;BTRNumberModel;1F;Constant1;SmallInteger;5;1;650;;;
		offset: (#V2;BTRNumberModel;1D;Constant1;SmallInteger;3;1;0;; @ #V2;BTRNumberModel;1D;Constant1;SmallInteger;3;1;0;;);
		color: #V2;BTRColorModel;32;Constant1;Color;1E;1;(Color r: 0.0 g: 0.0 b: 0.0);;.
	