initialization
initializeStyle

	self
		width: (World width / #V2;BTRNumberModel;51;N1;SmallInteger;3;1;2;SmallInteger;3;1;0;SmallInteger;5;1;100;SmallInteger;3;1;1;;);
		height: #V2;BTRNumberModel;55;N1;SmallInteger;5;1;650;SmallInteger;5;1;600;SmallInteger;5;1;700;SmallInteger;3;1;1;;;
		offset: (#V2;BTRNumberModel;51;N1;SmallInteger;3;1;0;SmallInteger;3;1;0;SmallInteger;5;1;100;SmallInteger;3;1;1;; @ #V2;BTRNumberModel;51;N1;SmallInteger;3;1;0;SmallInteger;3;1;0;SmallInteger;5;1;100;SmallInteger;3;1;1;;);
		color: #V2;BTRColorModel;32;Constant1;Color;1E;1;(Color r: 0.0 g: 0.0 b: 0.0);;.
	