initialization
initializeGround

	#V3;<~"98E%":+u-!!ElE@r,RpF!,OGEckl6F`M%"!!!!$"q!b4@ruF'DIIR2"98E%&I8@:!#GqA!!!**
$UJiTDe!KiFD5Z2"p[_;FCf)rEX2XF!!*3&!!!!*!!!!$$31&+3sGmfH#7#/C^:"@!!*3&!!!!"
!=8`+!!<Q.!!#(b##fVaBl7Ph!!!!""98E%!!*B+!!!*.!!!!\"qa.AEaa6)A4(9OCh7*uBl@kp
!!!!""98E%!!**,!!!!$$31&+3sH!c@:sIlFEM,*#QOi)!<`B&!!!<*!!!*.!!!!\"pIhABl8"u
!!!!$"98E%!"f6V&HR.`!!!!$$31&+3sH!hARfgjDJ*cs#QOi)!sAT(!!!T8DfTQ)Bl4Le@rHC*
ATA(W!!!*.!!!!\"r:-KEHPi1@qB(XCh5tPCi!ZmFD5Z2#QOi)!<`B&!!!<*!!!*.!!!!\"r'a>
EbAr[Df]W7Bm+&ZDKKH&ATA%V!!!$&z#ljr*!t##.!':Ap6<$iXF_tT!E_UI_AS_VP!!!9-z&J8M]
@q]Fa;flquAQ*\kBl7Pq$u^0#B5)6lCfFtjF:ee%Bk;KV@<>oi"a4<jF_)-nD/!m%D09\r@;L't
&I`MbG\M#;D,t(]F_)-iEHP]-FEMF,!!!!$$31&+3sH$YH$!UrH#7#/C^:"@!!*3&!!!!*!!!!$
$31&+3sGmb@VTIaF9hjH!!*3&!!!!*!!!!$$31&+3sH$ZDes6$@ruF'D?p4B!!*3&!!!!*!!!!$
$31&+3sH6_<)Q)%DKBo.DKJTkA7]Q_!!!!&"98E%!"&]+!N6>*!!0\=!!!&A$31&,dfBaT!!!*.
!!!!\"q+7JDffnn@VTIaF9hjH!!*3&!!!!*!!!!$$31&+3sGmaF_tT!EX2XF!!*3&!!!!*!!!!$
$31&+3sHEd<)Q"kF*)G2@rt%RDe!QWDe*Eq#QOi)"9\])!!!?+!!0#*!!!&3$31&,aUnr&F`:o4
@r,RpF(KD!!!!!$$31&++9VZE!"fJ:!!!fA!!!!$$31&+3skrf!([Fs!!9tC!!!!$$31&+3skrf
!o41`!!4SM!=8`+!!<Q.!!#(f!!!"O$31&+TE,?!!!!*.!!!!\$31&+TF(Z!!B:)\#ljr*!t##.
!':Mf!!(+J!!!'L#ljr*!t##.!':Mf!!,%d!!!'h#ljr*!t##.!':Mf!!)3i!!!'L#ljr*!t##.
!':Mf!!*B5!!!'L#ljr*!t##.!':Mf!!-U;!!!!i#ljr*!t##.!':Mf!!/)e!!!(3#ljr*!t##.
!':Mf!!3H6!!!"1#ljr*!t##.!':Mf!!4SV!!!(n#ljr*!t##.!':Mf!!5Rr!!!'L#ljr*!t##.
!':Mf!!6^=!!!)V!=8`+!!<Q.!!#(f!!!(n&HcobC^C(A!!<Q.!!#(f!!!):$31&+aU%qI!!<Q.
!!#(f!!!"1$31&+K*_MX!!io3!!/)\!<E<'!!!!%z"98E%A-;l4!!*~> to: #V3;<~"98E%":+u-!!ElE@r,RpF!,OGEckl6F`M%"!!!!$"q!b4@ruF'DIIR2"98E%'*nR<!%S'V!!!!$
"q*_<F)PQ&@<?4%D?^>;DKKH&ATA%V!!!$&z#ljr*!t##.!'CGt6#q!SH"CMRDes6$@ruF'D?p4B
!!*3&!!!!*!!!!$$31&+49cR"AT;j(DI[6d@VfUCDes6$@ruF'D?p4B!!*3&!!!!*!!!!$$31&+
49c!c@VTIaF9hjH!!*3&!!!!"#ljr*!t##.!'CGi:3CD_ATA%V!!!$&z!<E3%#ljr*!t##.!'CGl
9jq[PBlnK.AI&89!!*3&!!!!"#ljr*!t##.!'CH"9OVsSAPd;dBln'4AP$c]AS5Rp#QOi)!<`B&
!!!<*!!!*.!!!!]"pIJ4Ddd_n!!!!""98E%!!rW*!!<Q.!!#+c$:A`JCh7*uBl@kp!!!!""98E%
!!**$!=8`+!!<Q.!!#+c$r_"OChuRWDdd`G1^F']!!*3&!!!!*!!!!$$31&+49c0iEc6&<:L\'M
@rqtV!!!$&z!<E3-!!!!$$31&+49c*iARfgjDJ*cs#QOi)!sAT(!!!T8DfTQ)Bl4Le@rHC*ATA(W
!!!*.!!!!]"qEt!;GM@O@V'RSDe*Eq#QOi)#Qt,-!!!TC@prk\ARn_]DfTDfFE2)5B+YPjEbT0#
DII?\AU&;/#^0onG=5k]@1`Zd@;L't&I`MjDJ<s1D,t(]F_)-nD..['D09\r@;L't&I3;u@;^10
D$^1B!!<Q.!!#+c$:9#[AQ*kk@W-&g!!!!""98E%!!rW*!!<Q.!!#+c&40>o6Z6j`FCB'/9lFQR
C^:"@!!NK*!!!!+!!!'1$31&-+US2L!\Xl\!!5.e!!!!$$31&+49cNe<)Q"kF*)G2@rt%RDe!QW
De*Eq#QOi)"9\])!!!?+!!3W;!!!'D$31&-0*)@Z!!!*.!!!!]"pS"OD.7F"#QOi)!<`B&!!!<*
!!!*.!!!!]"pS"JEbTE(#QOi)!<`B&!!!$#!=8`+!!<Q.!!#+c"]0,ODKH-a!!!*(z&HR+g!I4\H
!<E3%&I``'E+O'"CghC+ATJ.X!!!*.!!!!A"98E%'*nR<!%S'V!!!!$$31&+4:2&g!(dLt!!(RV
!!!!$$31&+4:2&g!+lQ<!!%ub!!!!$$31&+4:2&g!0%<c!!-:1!!!!$$31&+4:2&g!4`F:!!/bo
#ljr*!t##.!'CSg!!(RW!!!#m!<E3%#ljr*!t##.!'CSg!!)^"!!!#0!=8`+!!<Q.!!#+g!!!$8
$31&+8I5@s!!<Q.!!#+g!!!$b$31&+ed2<V!!<Q.!!#+g!!!%($31&+\H)^3!=8`+!!<Q.!!#+g
!!!%L$31&,5R@Dj!!<Q.!!#+g!!!%n&HcobC]OP;#ljr*!t##.!'CSg!!1%G!!!#0#ljr*!t##.
!'CSg!!2^!!!!(]#ljr*!t##.!'CSg!!7'G!!!*(#ljr*!t##.!'CSg!!82g!!!)B#ljr*!t##.
!'CSg!!:7L!!!#0!=8`+!!<Q.!!#+g!!!*($31&.+:/#J!!<Q.!!#+g!!!*D$31&+AcVo5#ljr*
!t##.!'CSg!!>Fm!!!#0!<E3%!<EK,!!!93!!!&l!<E325Zn'ez"98E%A-;l4!6>9C!!!$~> do:
		[ :each | 
			| platform |
			platform := BMGround new.
			self addMorph:
				(platform relativePosition: (platform width * each) @ (self height - platform height)).
			self addGameObject: platform.]