defaults
defaultForm

	^ #V2;BTRImageModel;3E1;Constant2;Dictionary;14;1;((Dictionary new));Form;3AA;Form1;<~M,6r;%14!\!!!!.8Ou6I!!!!:!!!!9#R18/!"ZJ<`W,u?Vb'9B<-V`OPtad`@2R%US__e4P?bMd
k$ePBii^hciaPIb;4s_?p(E'b8ti3ITSJ?Ucu@h)_[\t?\ZFAY&%\Qf#FG)4-Ui.A;O8dmKPP`:
GPh-Ij37'T47g$Q0Dp'-k'`iapWguEn!)J4TdHDZ:D7(<N:QM>DNm+Ir#d-?'63nVMECJP`M1Dr
`>"Y@5MW@4>]3Y.4VB7Z^Ducp`A2<f.sq%P,120uFVS83j\Ad?alqJ[/X1AS.oA[=N8so[cZF#)
<89pLYf*[rl`o.'`4kpI3#Yb9ZJLL-V!nk?88rfD*VQtMUXnhJWIU=pbnI4&X2r6rl#0Z/eq/GQ
e?r',gq?R3Hj7&`<4JJ/FEVhBEA;rW_)ki/lKI.,Z+pSRk`Pp;kQ-=m-sR62%m-]=]]>eY6Mr+g
r7t&6T/A9!<>?b#'\_%lFOX?)N2FVRG.U0U`\g++'9dU&:ah!9334,21jHC46q#GJ'h(DF)APhu
M,G\B=fiT0_RKO&P%7+Mn1Ed0@jUrG]cXk_)%Y=AfsMW?NjNQ*@s6*60,WGX^XRsE2(QgJm+A<`
s,.U<CmK\Tio(>88^=QB`+j7qYo;l-L[ZM@D9HIk6R58;IE"$k9`-fdmc+-@/',trg[]@LS@55q
nqdML0fg/l[T5$8WYahr6@hFGD@CpLM0cA,f9AmDrb1bV\&96D;,Ita+d9Rio?pZdUX<=7;i/49
0j`+2_Xuo74Fbom/DON;pt%[Q9O6#b?d9(1bKCI/lur7U?GMXJ8L(Tj'@$4WZ5J,b:Jp6HjC?EE
78"&"fqJ)[hHtR6RBcZ8luMG<jht:f'$Ymb1eE!0kJhfOE=52'9#(3BOgVte44qK"1Dfrsn:?Ci
nSLp,z8OZBBY!QNJ~>;;