as yet unclassified
colorMorphIcon

	^ #V2;BTRImageModel;210;Constant1;Form;1FC;Form1;<~M,6r;%14!\!!!!.8Ou6I!!!!-!!!!-#R18/!*45Ik5YJ_:e=&@<-V_,N]fqM;&%",)es=d_8TCd
2`I(DEO/XJOhs[$*,;rL>Qegq8d%GUFr.,DC8bG75l)=4W56`PnFV(r?c2?'Hga&Zh.Q)`AFoo3
Z5PtAM@eAHdj/bX<M;]qbe%D8>j*'FN8$O(PYd`g""N6Qa$+Htq$#D]FUqct>7gJ2Q_4LFDFS%#
!94n;Jk]8ZY3Tal3DO3._@?15%l?#Kg!E/8s5.U-c+e(;"`Mn3=SaZc0nJ#43k-l;%[RRIqLk9!
VWcM5&fBU>Kod!\hVhe,UIK;1Vpp.)i(L+/0I>t)BF>Ru;ZhalRPO5-n$BhJfBGqXk"B?q?Z8CU
!t8(hK`W4a"=h]U%aeAXq@(XTQ-iR8.E4fF%9;Zto]WL+\c;[D;]jg]ZY1oB'Oem#H3,=M:[$41
$it\b#LioJ;b+Xg(W9is08ru,!WW3#!(fUS7'8jaJc~>;;