as yet unclassified
greetingMorphIcon

	^ #V3;<~"98E%":+u-!!ElE@r,RpF!,OGEckl6F`M%"!!!!$"q!b4@ruF'DIIR2"98E%)$g3B!%S'V!!!!$
"q*_<F)PQ&@<?4%D?^>;DKKH&ATA%V!!!$&z#ljr*!t##.!'CGt6#q!SH"CMRDes6$@ruF'D?p4B
!!*3&!!!!*!!!!$$31&+49cR"AT;j(DI[6d@VfUCDes6$@ruF'D?p4B!!*3&!!!!*!!!!$$31&+
49bsTEcPT6#QOi)!<`B&!!!<*!!!*.!!!!]"qX=6F(f,q6Z6dWARfgrDf,g\!!!*(z&I!8bCi"A/
"^uFl@<i.Z!!!*.!!!!]"p@D6Ebu'^!!!3+z&HlQWFE8#tGA1T0BFtG^ASGdjF:e[eAT2a)&I*/c
AohO*#ljr*!t##.!'CSg!!",I!!!!$"98E%!"&]+!:U<q!!)a"!!!!$$31&+49c6]<)Q;)@:s.G
De*Eq#QOi)"U"f*!!!TC@prk\ARn_]DfTDfFE2)5B+YPjEbT0#DII?\AU&;/#^0onG=5k]@1`Zd
@;L't#ljr*!t##.!'CGi:L\'M@rqtV!!!$&z#ljr*!t##.!'CGi:3CD_ATA%V!!!$&z#ljr*!t##.
!'CGl9jq[PBlnK.AI&89!!*3&!!!!"#ljr*!t##.!'CH"9OVsSAPd;dBln'4AP$c]AS5Rp#QOi)
!<`B&!!!<*!!!*.!!!!]"q!_9Ci!ZmFD5Z2#QOi)!<`B&!!!$#!<E3%#ljr*!t##.!'CGn:i^Jr
DbjhWARfff!!!!""98E%!!**$#ljr*!t##.!'CGl;Is?[@;]^oAI&89!!<?(!!!!2#&eNrB5)5q
#%MRlDImhp!!!!$$31&+49c?`<)Q)%DKBo.DKJTkA7]Q_!!!!&"98E%!"&]+!J1XY!!/>l!!!%p
$31&,XU+t-!!<Q.!!#+c$:9#[AQ*kk@W-&g!!!!""98E%!!rW*!!<Q.!!#+c$:9#[AQ*\kBl7Ph
!!!!""98E%!!rW*!!<Q.!!#+c'gbkt6"4nWEa`I"6>URMCJA_XAS_VP!!!-)z$31&,JdMJX!L3ul
!!/i$!!!!$$31&+49c6_Ble60@<kRYA8-1'#QOi)!<`B&!!!<*!!!*.!!!!]"pS"OD.7F"#QOi)
!<`B&!!!<*!!!*.!!!!]"pS"JEbTE(#QOi)!<`B&!!!$#!=8`+!!<Q.!!#+c"]0,ODKH-a!!!*(
z&HR+g!I4tO!!!*.!!!!]"q<t7F)Yr(Gu%maARfff!!!!""98E%!!**$!=8`+!!<Q.!!#+c#"!$G
D..Ah!!!!""98E%!"fW\F`:o4@r,RpF(KD!!!!!$$31&++9VZE!#Z%B!!"MM#ljr*!t##.!'CSg
!!#Rt!!!&R#ljr*!t##.!'CSg!!$U<!!!"Y#ljr*!t##.!'CSg!!%uc!!!'c#ljr*!t##.!'CSg
!!(LU!!!'c#ljr*!t##.!'CSg!!0e@!!!(4#ljr*!t##.!'CSg!!*?4!!!+<#ljr*!t##.!'CSg
!!'P:!!!"2#ljr*!t##.!'CSg!!",K!!!#K#ljr*!t##.!'CSg!!1d\!!!&n#ljr*!t##.!'CSg
!!-d@!!!)2#ljr*!t##.!'CSg!!2d#!!!&6!=8`+!!<Q.!!#+g!!!'9$31&+8I5@s!!<Q.!!#+g
!!!'c$31&,^&\68!<E3-!!!!$$31&+4:2&g!bN#HDJ<nf!<EK,!!!*.!!!!]$31&-M@'=`!PSj?
!!!*.!!!!]$31&-\I&<:"#C5`!!!*.!!!!]$31&-o*PHt"-<fh!!!*.!!!!]$31&.'++^>"0;e/
!!!*.!!!!]$31&.1C=*^!PSj?!!!*.!!!!]$31&.D$g7C"7-<o!!!*.!!!!]$31&.O9tsf"0;e/
!!!*.!!!!]$31&.X9nq-!+l64!=8`+!!<Q.!!#+g!!!,E$31&,^'Oc>!!<Q.!!#+g!!!,f$31&,
^&\68!=8`+!!<Q.!!#+g!!!-8$31&+AdJG;!!N]0!!-dG^]4A[6Z6j`FCB'/1-7m<@ruF'DIIR2
4#&QR0fpd36tp.QBl@ltEd8dFAToRP4%=./D*'a;4%=./D)"+7ISD@OE]YR%1a-*I+X&!]3)=ZT
8Kf6#+Y=i\+X&E^;DC-a+Y#<+8S^1d8mX>#<bO!G/QQ4^2,Z@rD]p9,@nAO[8M=I5>&$05%;.Cs
@OF)^D_XI:BJN[[6;:!J.ks^k4)mVg=#<TO>")[XDF7Ja0d\M.4#g4`=&(tQF"\[qH8n](6:+fu
;,0`45!&cO!!!!$$31&++9VZE!!!9)!!!0'!<E3%#ljr*"pt>1!=0'`]oWg+(&njG&cW@@!!!!&
rt,57rs/Q(!!!?*%fZM/!!WB7!!WB-rr<$!$3(M8!!!!&rt,5;rs/Q(!!!o:&HE.;(B4@7!"&Z;
!"&Z8rr<$!"oeu1!!!$!s8W*6!!WB4rr<$!"oeu1!!!$!s8W*6!!WBArr<$!s8W-!rr<$!s8W-!
rr<$!s8W-!'`\F;&,uV0!<<*!s8N'!!"JrC!!WB9rr<$!s8W-!rr<$!s8W-!*<6iS%0-M2!!!E1
!!!!-"98E%+9;~>