as yet unclassified
planets

	^ {
		#Mercury -> {0.387. 0.21. 0.2408. 2.44. Color silver. {}}.
		#Venus -> {0.723. 0.00067. 0.6152. 6.05. Color green. {}}.
		#Earth -> {1. 0.017. 1. 6.371. Color blue. 
			{#Moon -> {3.844/(40). 0.0555. 1/12. 1.7. Color gray. {}}} asDictionary}.
		#Mars -> {1.52. 0.094. 1.881. 3.39. Color red. {}}.
		#Jupiter -> {5.20. 0.049. 11.86. 69.9. Color white. {}}.
		#Saturn -> {9.58. 0.057. 29.46. 58.2. Color brown. {}}.
		#Uranos -> {19.2. 0.046. 84.01. 25.4. Color seaFoam. {}}.
		#Neptune -> {30.1. 0.011. 164.8. 24.6. Color blue darker. {}}.
	} asDictionary