as yet unclassified
example6

	Transcript showln: 'Halt after printing this.'.
	#V3;<~"98E%":+u-!!ElE@r,RpF!,OGEckl6F`M%"!!!!$"q!b4@ruF'DIIR2"98E%&-r79!#GqA!!!**
$UJiTDe!KiFD5Z2"p[_;FCf)rEX2XF!!*3&!!!!*!!!!$$31&+3sH<a<)Q&'ART@nDeX*29lFQR
C^:"@!!WQ+!!!!2&S#6ZBOt^QFDl22;fm%oDJ'OiDfTQ)Bl7?q<+U;r&I<PoATpONFC>adAStpc
Ch7,h"E/0fAI/>:!!<Q.!!#(b##fea@W-&g!!!!""98E%!!*B+!!!*.!!!!\"pS"JEbTE(#QOi)
!<`B&!!!$+!!!!$$31&+3sH9_EcPT6ARn/HCi!ZmFD5Z2#QOi)!<`B&!!!$##ljr*!t##.!':Ak
9jq[PBlnK.AI&89!!*3&!!!!*!!!!$$31&+3sGjbDeX*2#QOi)!sAT(!!!T3GS't%#ljr*!t##.
!':Ak;Is?[@;]^oAI&89!!<?(!!!!2#&eNrB5)5q#%MRlDImhp!!!!$$31&+3sHI!AT;j(DI[6d
@VfUCDes6$@ruF'D?p4B!!*3&!!!!*!!!!$$31&+3sHBm@<-!l:iCDhFD5o08T&W]B4Z)h!!!!"
"98E%!!*B+!!!*.!!!!\"q!\BFCeBrD.7F"#QOi)!<`B&!!!<*!!!*.!!!!\"pRk4C1Ums#QOi)
!<`B&!!!<*!!!*.!!!!\"q!_9Ci!ZmFD5Z2#QOi)!<`B&!!!$##ljr*!t##.!':Am:i^JrDbjhW
ARfff!!!!""98E%!!rW*!!<Q.!!#(b##9;X@V'Qc!!!!""98E%!!rW*!!<Q.!!#(b'gbkt6"4nW
Ea`I"6>URMCJA_XAS_VP!!!-)z$31&+K*hSY!1!rl!!&f,%!-Q1ATD9s@<6L$EsVgH!!<Q.!!",E
!!!!1#QOi)(C:'A!!<Q.!!#(f!!!!i$31&-D[?CD!!<Q.!!#(f!!!"1$31&-M[9@`!!<Q.!!#(f
!!!(Y$31&-&-3(;!!!*.!!!!\$31&+j9bke!<E3-!!!!$$31&+3skrf!<EN-!!/Jg!=8`+!!<Q.
!!#(f!!!$L$31&-&.&=:!!<Q.!!#(f!!!%f$31&-/-u:V!!<Q.!!#(f!!!$k$31&-&.&=:!!<Q.
!!#(f!!!%7$31&-&.&=:!!<Q.!!#(f!!!&=$31&+8-'"s!!!*.!!!!\$31&,n-T-q!65BG!!!*.
!!!!\$31&-&./C;!_s%%!!!*.!!!!\$31&-/.)@W!Y>A5#ljr*!t##.!':Mf!!5n-")_gh#ljr*
!t##.!':Mf!!7'G!!!$L#ljr*!t##.!':Mf!!(%H!!!#[#ljr*"pt>1!+c03!<N<~>.
	Transcript showln: 'I was halted before printing this.'.