as yet unclassified
example9

	^ #V3;<~"98E%":+u-!!ElE@r,RpF!,OGEckl6F`M%"!!!!$"q!b4@ruF'DIIR2"98E%'*nR<!%S'V!!!!$
"q*_<F)PQ&@<?4%D?^>;DKKH&ATA%V!!!$&z#ljr*!t##.!'CGt6#q!SH"CMRDes6$@ruF'D?p4B
!!*3&!!!!*!!!!$$31&+49cR"AT;j(DI[6d@VfUCDes6$@ruF'D?p4B!!*3&!!!!*!!!!$$31&+
49c!c@VTIaF9hjH!!*3&!!!!"#ljr*!t##.!'CGi:3CD_ATA%V!!!$&z!=8`+!!<Q.!!#+c"[d3E
DfQ*`!!!-)z&Hd&d@M&uX@:Nt^A41!JFD)6t@prk\ARn,AFAQCfFCfK1!<EK,!!!*.!!!!]"pn"4
B5VF*F_#%h!!!!""98E%!!*B+!!!*.!!!!]"r'a>EbAr[Df]W7Bm+&ZDKKH&ATA%V!!!$&z#ljr*
!t##.!'CGm6Z6dWARfgrDf,g\!!!$&z!<E3%!<EK,!!!*.!!!!]"q+7JDffnn@VTIaF9hjH!!*3&
!!!!"!<EK,!!!*.!!!!]"pn1=@ru-sB5D,b!!!!$"98E%!"fEREbT0#D@m(_DfT`,EX;^G!!<Q.
!!#+c&40>o6Z6j`FCB'/9lFQRC^:"@!!NK*!!!!2&S#6ZBOt^QFDl22;fm%oDJ'OiDfTQ)Bl7?q
<+U;r&I<PoATpONFC>abG%#30AI/>:!!<Q.!!#+c$:9#[AQ*kk@W-&g!!!!""98E%!!rW*!!<Q.
!!#+c'gbkt6"4nWEa`I"6>URMCJA_XAS_VP!!!-)z$31&-'++^>![\6S!!4t`!!!!$$31&+49c6]
<)Q)%Ci=>gDe*Eq#QOi)"U"f*!!!?+!!3f@!!!'I$31&-1^X3_!^6Vk!!!!$$31&+49c!gH#7#/
C^:"@!!*3&!!!!*!!!!$$31&+49c!gFE2)5B*\J;!!*3&!!!!"!<EK,!!!*.!!!!]"pIhABl8"u
!!!!$"98E%!"f6V&HR.X!<E3%#ljr*!t##.!'CGi6>:OY@;lJP!!!$&z&I``'E+O'"CghC+ATJ.X
!!!*.!!!!A"98E%'*nR<!%S'V!!!!$$31&+4:2&g!(dLt!!(RV!!!!$$31&+4:2&g!+lQ<!!%ub
!!!!$$31&+4:2&g!0%<c!!.NT!!!!$$31&+4:2&g!4`F:!!/kr#ljr*!t##.!'CSg!!(RW!!!$V
!=8`+!!<Q.!!#+g!!!#j$31&+\H)^;!!!!$$31&+4:2&g!Ak,`!!'P1#ljr*!t##.!'CSg!!-%+
!!!!j#ljr*!t##.!'CSg!!.NU!!!#0!<E3%!<EK,!!!*.!!!!]$31&,U_*]HBl!eN!=8`+!!<Q.
!!#+g!!!&@$31&+\Hr69!!<Q.!!#+g!!!&o$31&-D[?CD!!<Q.!!#+g!!!'r$31&-i<]Ja!!<Q.
!!#+g!!!(=$31&+\Hr69!!<Q.!!#+g!!!)"$31&,pAkR#!!!*.!!!!]$31&-i<fPb!rWE*!!!*.
!!!!]$31&-r<`N)!+l64!=8`+!!<Q.!!#+g!!!*@$31&+\H)^3!<EK,!!!*.!!!!]$31&.64*\m
!+lN;!!!00!!!)"!<E3-!!!!%$31&+o)o%(rW33&!!",LJ-H#ZrrE(L~>