as yet unclassified
example6

	Transcript showln: 'Halt after printing this.'.
	#V3;<~"98E%":+u-!!ElE@r,RpF!,OGEckl6F`M%"!!!!$"q!b4@ruF'DIIR2"98E%&I8@:!#GqA!!!**
$UJiTDe!KiFD5Z2"p[_;FCf)rEX2XF!!*3&!!!!*!!!!$$31&+3sH<a<)Q&'ART@nDeX*29lFQR
C^:"@!!WQ+!!!!2&S#6ZBOt^QFDl22;fm%oDJ'OiDfTQ)Bl7?q<+U;r&I<PoATpONFC>adAStpc
Ch7,h"E/0fAI/>:!!<Q.!!#(b'gbkt6"4nWEa`I"6>URMCJA_XAS_VP!!!-)z$31&+K*hSY!1!rl
!!&f$!!!!$$31&+3sGmfH#7#/C^:"@!!*3&!!!!*!!!!$$31&+3sGmfFE2)5B*\J;!!*3&!!!!"
#ljr*!t##.!':As6#q!SH"CMRDes6$@ruF'D?p4B!!*3&!!!!"!=8`+!!<Q.!!#(b#u+i@DJ=38
A7Z#H!!!$&z#ljr*!t##.!':Ag:iC&cF9hjH!!<?(!!!!2!I,1WGmOHN!!<Q.!!#(b#uY>EFCB'"
Ch3kP!!!*(z&I*/oBkM-t&I)``Ec,H/#ljr*!t##.!':B#;e9rkASu!h@:F%a6Z6dWARfgrDf,g\
!!!$&z#ljr*!t##.!':B!9OVsSAPd;dBln'4AP$c]AS5Rp#QOi)!<`B&!!!$+!!!!$$31&+3sH$Y
H$!UrH#7#/C^:"@!!*3&!!!!*!!!!$$31&+3sGmb@VTIaF9hjH!!*3&!!!!*!!!!$$31&+3sH$Z
Des6$@ruF'D?p4B!!*3&!!!!"!=8`+!!<Q.!!#(b$:9#[AQ*\kBl7Ph!!!!""98E%!!rW*!!<Q.
!!#(b##9;X@V'Qc!!!!""98E%!!rW*!!<Q.!!#(b$W(k^FDjraC1Ums#QOi)!<`B&!!!T>F*2G5
EarooF)to6#ljr*!t##.!$DCE!!!T:!!!!8#ljr*!t##.!':Mf!!#Os!!!(u#ljr*!t##.!':Mf
!!$R;!!!#>#ljr*!t##.!':Mf!!9&*!!!%0#ljr*!t##.!':Mf!!:%M")_gh#ljr*!t##.!':Mf
!!+)I!!!$\!=8`+!!<Q.!!#(f!!!$\$31&,dK'@T!!!!$$31&+3skrf!FlH:!!5^u!!!!$$31&+
3skrf!J1XY!!5^u!!!!$$31&+3skrf!M]u%!!5^u!!!!$$31&+3skrf!R_;T!!6^<!!!!$$31&+
3skrf!WEE+!!#Oj#ljr*!t##.!':Mf!!4SV!!!$##ljr*!t##.!':Mf!!5_!!!!)<#ljr*!t##.
!':Mf!!6^=!!!'l!<EK,!!!*.!!!!\$31&-LC+"]!?DIH!!!*.!!!!\$31&+`sMeH!_E[u!!!*.
!!!!\$31&,!=Af,!?DIH!!!31!!!"1&HtKt0fq/l!<N<~>.
	Transcript showln: 'I was halted before printing this.'.