as yet unclassified
example5

	^ #V3;<~"98E%":+u-!!ElE@r,RpF!,OGEckl6F`M%"!!!!$"q!b4@ruF'DIIR2"98E%('jm?!%S'V!!!!$
"q*_<F)PQ&@<?4%D?^>;DKKH&ATA%V!!!$&z#ljr*!t##.!'CGt6#q!SH"CMRDes6$@ruF'D?p4B
!!*3&!!!!*!!!!$$31&+49cR"AT;j(DI[6d@VfUCDes6$@ruF'D?p4B!!*3&!!!!*!!!!$$31&+
49c?f@<6*nA4(9OCh7*uBl@kp!!!!$"98E%!"fBV@;Kb*&HuT`Eaa5"!!!!$$31&+49bsTEcPT6
#QOi)!<`B&!!!<*!!!*.!!!!]"pRk4C1Ums#QOi)!<`B&!!!<*!!!*.!!!!]$31&++:%rI!!<?(
!!!!+!!!#L$31&+g^*r\!!<Q.!!#+c"[d3EDfQ*`!!!-)z&Hd&d@M&uX@:Nt^A41!JFD)6t@prk\
ARn,AFAQCfFCfK1#ljr*!t##.!'CGi:3CD_ATA%V!!!$&z!=8`+!!<Q.!!#+c#u+i@DJ=38A7Z#H
!!!$&z!=8`+!!<Q.!!#+c'MMqUB4XnXF(o`1G%F6_FCf)rEX2XF!!*3&!!!!*!!!!$$31&+49c-[
Des6$@ruF'D?p4B!!*3&!!!!"!<E3%!=8`+!!<Q.!!#+c$W(k^FDjraC1Ums#QOi)!<`B&!!!$#
!=8`+!!<Q.!!#+c#uY>EFCB'"Ch3kP!!!*(z&I*/oBkM-t&I)``Ec,H/#ljr*!t##.!'CGs6<$iM
Df0W<@;^0]De*Eq#QOi)"U"f*!!!TC@prk\ARn_]DfTDfFE2)5B+YPjEbT0#DII?\AU&;/#^0on
G=5k]@1`Zd@;L't#ljr*!t##.!'CGm6@!Za;gE4hDeo[Z!!!$&z#ljr*!t##.!'CGp6<$iMDes?4
9lFQRC^:"@!!NK*!!!!+!!!(P$31&-PmRKk!i$)&!!98/!!!!$$31&+49c-ZH$!UrFE2)5B*\J;
!!*3&!!!!*!!!!$$31&+49cNe<)Q"kF*)G2@rt%RDe!QWDe*Eq#QOi)"9\])!!!?+!!7`Z!!!(c
$31&-UBpo#!!<Q.!!#+c##fea@W-&g!!!!""98E%!!rW*!!<Q.!!#+c##fVaBl7Ph!!!!""98E%
!!**$#ljr*!t##.!'CGh:iC&cF9hjH!!<?(!!!!2!I,1WGl[pH!<E35%!-Q1ATD9s@<6L$EsVgH
!!<Q.!!",E!!!!7#QOi).ffqV!!!*.!!!!]$31&+8I>Ft!JUm\!!!*.!!!!]$31&+AdSM<!0%9b
!!!*.!!!!]$31&+N=#Xc!UU0n!!!*.!!!!]$31&+\I&<:!UU0n!!!*.!!!!]$31&,#RUP3!YYk?
!!!*.!!!!]$31&+m0Wgn!+lN;!!!*.!!!!]$31&++:8)K!4`C9!!!*.!!!!]$31&,L'dn\!M]r$
!!!*.!!!!]$31&,7g]4r!=/]4!!!!$$31&+4:2&g!M]u%!!*?+#ljr*!t##.!'CSg!!0tE!!!!j
#ljr*!t##.!'CSg!!2Ho!!!$*!<E3%!<EK,!!!*.!!!!]$31&-'+k=aBl!eN!=8`+!!<Q.!!#+g
!!!'Z$31&,#RLJ2!!<Q.!!#+g!!!(4$31&.2$j6_!!<Q.!!#+g!!!)7$31&.D[?CD!!<Q.!!#+g
!!!)W$31&-AdJG;!!<Q.!!#+g!!!*9$31&.M[9@`!!<Q.!!#+g!!!*Y$31&,#RLJ2!!<Q.!!#+g
!!!+>$31&.M[9@`!!<Q.!!#+g!!!+Z$31&+AcVo5#ljr*!t##.!'CSg!!B5.!!!$*!<E3%!<EK,
!!!00!!!)W&QM2:DKBo.DKIWq6tp.QBl@ltEd9`$1cmER-n%Jt@ruF'DIIR2+Dtb7.4I>GDes?4
4#'/c0fpdNDes?4+EBLc0J5%%B0%.i+C[AS0J54:1+>9c#ljr*!t##.!$DCE!!!!)!!!!&!<E3%
!=8`+!!EW/!!,Rm!"]&1!<E~>