as yet unclassified
example6
	<BTRBlockModel>
	^ #V2;BTRBreakpoint;1EC;1;(BTRBreakpoint basicNew instVarAt: 1 put: ((Dictionary new) add: (#sourcePointer->136066796); add: (#compiledMethodProperties->((AdditionalMethodState basicNew: 1)  instVarAt: 1 put: nil; instVarAt: 2 put: #example6; basicAt: 1 put: (Pragma basicNew instVarAt: 1 put: nil; instVarAt: 2 put: #BTRBlockModel; instVarAt: 3 put: #(); yourself); yourself)); add: (#selector->#example6); add: (#methodClass->BTRExample class); yourself); instVarAt: 2 put: true; instVarAt: 3 put: false; yourself);