as yet unclassified
sm
	<BTRBlockModel>
	^ #V2;BTRStateMachineModel;254;StateMachine1;Dictionary;1E2;1;((Dictionary new) add: (BTRStateMachineGraphicalEditorMorph->((Dictionary new) add: (#extent->(1320@318)); add: (#states->((Dictionary new) add: (#'New State'->((Dictionary new) add: (#position->(490@100)); yourself)); add: (#Start->((Dictionary new) add: (#position->(90@100)); yourself)); yourself)); add: (#transitions->((Dictionary new) add: ((#Start->#foo)->((Dictionary new) add: (#startDock->#bottom); add: (#endDock->#bottom); yourself)); yourself)); yourself)); yourself);#Start -> {
	#'bar bar' -> #'New State'.
	#foo -> #'New State'}.
#'New State' -> {}.;