as yet unclassified
sm1
	<BTRBlockModel>
	^ #V2;BTRStateMachineModel;391;StateMachine1;Dictionary;2FE;1;((Dictionary new) add: (BTRStateMachineGraphicalEditorMorph->((Dictionary new) add: (#extent->(1181@376)); add: (#states->((Dictionary new) add: (#'New State 2'->((Dictionary new) add: (#position->(880@160)); yourself)); add: (#'New State'->((Dictionary new) add: (#position->(550@140)); yourself)); add: (#'New State 3'->((Dictionary new) add: (#position->(380@300)); yourself)); add: (#Start->((Dictionary new) add: (#position->(90@100)); yourself)); yourself)); add: (#transitions->((Dictionary new) add: ((#'New State 2'->#fasd)->((Dictionary new) add: (#startDock->#bottom); add: (#endDock->#bottom); yourself)); add: ((#'New State'->#asdf)->((Dictionary new) add: (#startDock->#bottom); add: (#endDock->#bottom); yourself)); yourself)); yourself)); yourself);#Start -> {}.
#'New State' -> {
	#asdf -> #Start}.
#'New State 2' -> {}.
#'New State 3' -> {
	#fasd -> #'New State'}.;