as yet unclassified
sm1new
	<BTRBlockModel>
	^ #V2;BTRStateMachineModel;32D;StateMachine1;Dictionary;2A9;1;((Dictionary new) add: (BTRStateMachineGraphicalEditorMorph->((Dictionary new) add: (#extent->(939@236)); add: (#states->((Dictionary new) add: (#'New State'->((Dictionary new) add: (#position->(400@100)); yourself)); add: (#'New State 2'->((Dictionary new) add: (#position->(670@60)); yourself)); add: (#Start->((Dictionary new) add: (#position->(90@100)); yourself)); yourself)); add: (#transitions->((Dictionary new) add: ((#'New State 2'->#asdf)->((Dictionary new) add: (#startDock->#top); add: (#endDock->#right); yourself)); add: ((#'New State 2'->#fasd)->((Dictionary new) add: (#startDock->#bottom); add: (#endDock->#bottom); yourself)); yourself)); yourself)); yourself);#Start -> {}.
#'New State' -> {}.
#'New State 2' -> {
	#asdf -> #'New State'.
	#fasd -> #'New State'}.;