as yet unclassified
sm2new
	<BTRBlockModel>
	^ #V2;BTRStateMachineModel;23D;StateMachine1;Dictionary;1C0;1;((Dictionary new) add: (BTRStateMachineGraphicalEditorMorph->((Dictionary new) add: (#extent->(1320@318)); add: (#states->((Dictionary new) add: (#'New State'->((Dictionary new) add: (#position->(550@140)); yourself)); add: (#'New State 2'->((Dictionary new) add: (#position->(880@160)); yourself)); add: (#Start->((Dictionary new) add: (#position->(90@100)); yourself)); yourself)); add: (#transitions->((Dictionary new))); yourself)); yourself);#Start -> {}.
#'New State' -> {
	#asdf -> #Start}.
#'New State 2' -> {
	#fasd -> #'New State'}.;