as yet unclassified
testing

	^ ImageMorph new asRescalingImageMorph
		color: #V2;BTRColorModel;32;Constant1;Color;1E;1;(Color r: 0.318 g: 0.0 b: 1);;;
		extent: #V2;BTRNumberModel;51;N1;SmallInteger;3;1;0;SmallInteger;3;1;0;SmallInteger;5;1;100;SmallInteger;3;1;1;; @ #V2;BTRNumberModel;52;N1;SmallInteger;4;1;97;SmallInteger;3;1;0;SmallInteger;5;1;100;SmallInteger;3;1;1;;;
		image: #V2;BTRImageModel;157;Constant1;Form;143;Form1;<~M,6r;%14!\!!!!.8Ou6I!!!!-!!!!-#R18/!*45Ik5YJ^^.C^Y<-V_Zq#?sC^]5PoSc/52p?>ra
]8lge?a8q;s/<?_rWfY'p>9rUfDgtFP&Li]!)iaej$,M0Idn6,&.l:>J+Wc\107Ea+Ho(uO\L"%
r:RhB_QX!Al48G',[#sJ1k69l9_DZl;%->._\T4M0l6oY$??nQZ.foX)FBB/&/me@6-dX0oc8ui
[s`m=OAdhifWK]3`]!.#K!Ek+P@2^?c<Um&$AJb4!(-iP5`l7q-kW3T3Mlg:0R>:_pY:H&!!!!j
78?7R6=>B~>;;;
		yourself