as yet unclassified
testing

	^ ImageMorph new asRescalingImageMorph
		color: #V2;BTRColorModel;31;Constant1;Color;1D;1;(Color r: 1 g: 0.42 b: 0.0);;;
		extent: #V2;BTRNumberModel;1E;Constant1;SmallInteger;4;1;54;; @ #V2;BTRNumberModel;1E;Constant1;SmallInteger;4;1;97;;;
		image: #V2;BTRImageModel;157;Constant1;Form;143;Form1;<~M,6r;%14!\!!!!.8Ou6I!!!!-!!!!-#R18/!*45Ik5YJ^^.C^Y<-V_Zq#?sC^]5PoSc/52p?>ra
]8lge?a8q;s/<?_rWfY'p>9rUfDgtFP&Li]!)iaej$,M0Idn6,&.l:>J+Wc\107Ea+Ho(uO\L"%
r:RhB_QX!Al48G',[#sJ1k69l9_DZl;%->._\T4M0l6oY$??nQZ.foX)FBB/&/me@6-dX0oc8ui
[s`m=OAdhifWK]3`]!.#K!Ek+P@2^?c<Um&$AJb4!(-iP5`l7q-kW3T3Mlg:0R>:_pY:H&!!!!j
78?7R6=>B~>;;;
		yourself