as yet unclassified
testing

	^ ImageMorph new asRescalingImageMorph
		color: #V2;BTRColorModel;57;Constant2;Dictionary;14;1;((Dictionary new));TranslucentColor;15;1;(Color transparent);;;
		extent: #V2;BTRNumberModel;51;N1;SmallInteger;3;1;0;SmallInteger;3;1;0;SmallInteger;5;1;100;SmallInteger;3;1;1;; @ #V2;BTRNumberModel;52;N1;SmallInteger;4;1;97;SmallInteger;3;1;0;SmallInteger;5;1;100;SmallInteger;3;1;1;;;
		image: #V2;BTRImageModel;45;Constant2;Dictionary;14;1;((Dictionary new));UndefinedObject;5;1;nil;;;
		yourself