as yet unclassified
z
	<BTRBlockModel>
	^ #V2;BTRStateMachineModel;24A;StateMachine1;Dictionary;1F0;1;((Dictionary new) add: (BTRStateMachineGraphicalEditorMorph->((Dictionary new) add: (#extent->(802@201)); add: (#states->((Dictionary new) add: (#'New State 2'->((Dictionary new) add: (#position->(720@40)); yourself)); add: (#'New State'->((Dictionary new) add: (#position->(70@40)); yourself)); yourself)); add: (#transitions->((Dictionary new) add: ((#'New State 2'->#test)->((Dictionary new) add: (#startDock->#bottom); add: (#endDock->#bottom); yourself)); yourself)); yourself)); yourself);#New State -> {}.
#New State 2 -> {
	#test -> #'New State'}.;